In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../results/aggregati_202425.csv')
df = df[(df['livello_aggregazione']=='plesso') & (df['tipo_gestione']=='tutte')]

In [3]:
df_geocoded = pd.read_csv('../data_processed/unita_202425.csv')

In [4]:
df_geocoded['ordine_scuola'].unique()

array(['SCUOLA SECONDARIA II GRADO', 'SCUOLA PRIMARIA',
       'SCUOLA SECONDARIA I GRADO'], dtype=object)

In [5]:
codici_scuola_localizzati = df_geocoded['codice_scuola'].unique()

In [6]:
codici_scuola_analizzati = df['codice_scuola'].unique()

In [7]:
df[df['codice_scuola'].isin(codici_scuola_localizzati)].sample(5).columns

Index(['anno_scolastico', 'livello_aggregazione', 'tipo_gestione', 'regione',
       'provincia', 'codice_comune', 'comune', 'codice_scuola',
       'denominazione_scuola', 'unita_totali', 'unita_sopra_30',
       'unita_sopra_30_irrisolvibili', 'studenti_totali_sopra_30',
       'studenti_non_italiani_sopra_30', 'm_min_sopra_30',
       'm_min_pct_non_italiani_sopra_30', 'm_min_pct_studenti_sopra_30',
       'm_min_con_sostituzione_legacy_sopra_30', 'studenti_totali_analizzati',
       'studenti_non_italiani_analizzati', 'm_min_pct_non_italiani_analizzati',
       'm_min_pct_studenti_analizzati', 'classi_esatte_sommate',
       'unita_con_chiave_classi_esatta', 'unita_senza_chiave_classi_esatta'],
      dtype='object')

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
df[df['codice_scuola'].isin(codici_scuola_localizzati)].sort_values(by='m_min_sopra_30', ascending=False)

,anno_scolastico,livello_aggregazione,tipo_gestione,regione,provincia,codice_comune,comune,codice_scuola,denominazione_scuola,unita_totali,unita_sopra_30,unita_sopra_30_irrisolvibili,studenti_totali_sopra_30,studenti_non_italiani_sopra_30,m_min_sopra_30,m_min_pct_non_italiani_sopra_30,m_min_pct_studenti_sopra_30,m_min_con_sostituzione_legacy_sopra_30,studenti_totali_analizzati,studenti_non_italiani_analizzati,m_min_pct_non_italiani_analizzati,m_min_pct_studenti_analizzati,classi_esatte_sommate,unita_con_chiave_classi_esatta,unita_senza_chiave_classi_esatta
59217,202425,plesso,tutte,LOMBARDIA,COMO,C933,COMO,COPM02000B,LICEO TERESA CICERI,5,2,0,445,398,379,0.952261,0.851685,265,1166,455,0.832967,0.325043,53,5,0
57145,202425,plesso,tutte,LIGURIA,GENOVA,D969,GENOVA,GEEE85101L,S.EL. - A.CANTORE -,5,5,0,634,443,364,0.821670,0.574132,256,634,443,0.821670,0.574132,26,5,0
60156,202425,plesso,tutte,LOMBARDIA,MILANO,A618,BARANZATE,MIEE8A901E,PRIMARIA G. RODARI,5,5,0,463,367,328,0.893733,0.708423,229,463,367,0.893733,0.708423,21,5,0
73450,202425,plesso,tutte,TOSCANA,PRATO,G999,PRATO,POMM80801C,BOGARDO BURICCHI,3,3,0,427,340,303,0.891176,0.709602,213,427,340,0.891176,0.709602,19,3,0
60648,202425,plesso,tutte,LOMBARDIA,MILANO,F205,MILANO,MIEE8C402N,PRIMARIA L. CADORNA,5,5,0,446,344,303,0.880814,0.679372,214,446,344,0.880814,0.679372,24,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56222,202425,plesso,tutte,LAZIO,ROMA,H501,ROMA,RMMM8CP01G,VIA CITTA S.ANGELO 31,3,0,0,0,0,0,NaN,NaN,0,422,28,0.000000,0.000000,20,3,0
56221,202425,plesso,tutte,LAZIO,ROMA,H501,ROMA,RMMM8CN01X,VIA CANTIANO 131,3,0,0,0,0,0,NaN,NaN,0,279,56,0.000000,0.000000,13,3,0
56220,202425,plesso,tutte,LAZIO,ROMA,H501,ROMA,RMMM8CM014,ITALO CALVINO,3,0,0,0,0,0,NaN,NaN,0,480,51,0.000000,0.000000,23,3,0
56219,202425,plesso,tutte,LAZIO,ROMA,H501,ROMA,RMMM8CK01C,"SMS ""LODOVICO PAVONI""",3,0,0,0,0,0,NaN,NaN,0,431,117,0.000000,0.000000,21,3,0
76702,202425,plesso,tutte,VENETO,VICENZA,M199,ZUGLIANO,VIMM83802G,"SMS ""G. GALILEI"" - ZUGLIANO",3,0,0,0,0,0,NaN,NaN,0,167,11,0.000000,0.000000,9,3,0

In [48]:
df = pd.read_csv('/home/sava1/MIM_30_percento_2024_25/data_raw/SCUANAGRAFESTAT20242520250831.csv')

In [11]:
df['DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA'].unique()

array(['SCUOLA PRIMO GRADO', 'SCUOLA PRIMARIA', 'CENTRO TERRITORIALE',
       'ISTITUTO COMPRENSIVO', 'ISTITUTO TECNICO INDUSTRIALE',
       'IST PROF PER I SERVIZI COMMERCIALI',
       'IST PROF INDUSTRIA E ARTIGIANATO', 'SCUOLA INFANZIA',
       'IST PROF PER I SERVIZI COMMERCIALI E TURISTICI',
       "IST PROF PER L'AGRICOLTURA E L'AMBIENTE",
       'IST PROF PER I SERVIZI ALBERGHIERI E RISTORAZIONE',
       'LICEO CLASSICO', 'ISTITUTO TECNICO COMMERCIALE',
       "ISTITUTO TECNICO PER ATTIVITA' SOCIALI (GIA' ITF)",
       'IST TEC COMMERCIALE E PER GEOMETRI', 'ISTITUTO SUPERIORE',
       'LICEO SCIENTIFICO', 'LICEO ARTISTICO', 'ISTITUTO MAGISTRALE',
       'ISTITUTO TECNICO PER GEOMETRI', "ISTITUTO D'ARTE",
       'CONVITTO ANNESSO', 'ISTITUTO TECNICO AGRARIO', 'EDUCANDATO',
       'ISTITUTO TECNICO PER IL TURISMO', "IST PROF PER L'AGRICOLTURA",
       'IST PROF PER I SERVIZI SOCIALI',
       'IST TECNICO ECONOMICO E TECNOLOGICO', 'ISTITUTO TECNICO NAUTICO',
       'IST PROF PER I SERVIZI TURISTICI',
       "IST PROF INDUSTRIA E ATTIVITA' MARINARE", 'SCUOLA MAGISTRALE',
       'CONVITTO NAZIONALE', 'IST PROF ALBERGHIERO',
       'IST PROF PER I SERVIZI COMM TUR E DELLA PUBB',
       'IST PROF INDUSTRIA E ARTIGIANATO PER CIECHI',
       'IST PROF INDUSTRIA E ARTIGIANATO PER SORDOMUTI',
       'IST PROF CINEMATOGRAFIA E TELEVISIONE',
       'ISTITUTO TECNICO AERONAUTICO',
       'IST PROF PER I SERVIZI PUBBLICITARI'], dtype=object)

In [12]:
df.columns

Index(['ANNOSCOLASTICO', 'AREAGEOGRAFICA', 'REGIONE', 'PROVINCIA',
       'CODICEISTITUTORIFERIMENTO', 'DENOMINAZIONEISTITUTORIFERIMENTO',
       'CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'INDIRIZZOSCUOLA', 'CAPSCUOLA',
       'CODICECOMUNESCUOLA', 'DESCRIZIONECOMUNE',
       'DESCRIZIONECARATTERISTICASCUOLA',
       'DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA', 'INDICAZIONESEDEDIRETTIVO',
       'INDICAZIONESEDEOMNICOMPRENSIVO', 'INDIRIZZOEMAILSCUOLA',
       'INDIRIZZOPECSCUOLA', 'SITOWEBSCUOLA', 'SEDESCOLASTICA'],
      dtype='object')

# Casi anomali da controllare nei dataset originali

Ogni sezione mostra le righe **grezze** (`data_raw/`) di uno dei fenomeni emersi dai controlli qualità.

In [50]:
import pandas as pd
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 250)

RAW = Path('../data_raw')
SUFFISSI = {'statale': ('STA', 'STAT'), 'paritaria': ('PAR', 'PAR')}


def leggi(nome):
    return pd.read_csv(RAW / nome, dtype=str, keep_default_na=False, encoding='utf-8-sig')


def carica(prefisso, gestione, anagrafe=False):
    suffisso = SUFFISSI[gestione][1 if anagrafe else 0]
    df = leggi(f'{prefisso}{suffisso}20242520250831.csv')
    df.insert(0, 'gestione', gestione)
    return df


# Flusso cittadinanza, flusso classi/studenti, anagrafe standard e autonome (statali + paritarie)
cit = pd.concat([carica('ALUITASTRACIT', g) for g in SUFFISSI], ignore_index=True)
cla = pd.concat([carica('ALUCORSOINDCLA', g) for g in SUFFISSI], ignore_index=True)
ana_std = pd.concat([carica('SCUANAGRAFE', g, anagrafe=True) for g in SUFFISSI], ignore_index=True)
ana_aut = pd.concat([carica('SCUANAAUT', g, anagrafe=True) for g in SUFFISSI], ignore_index=True)
ana_std['fonte'] = 'standard'
ana_aut['fonte'] = 'autonome'
ana = pd.concat([ana_std, ana_aut], ignore_index=True)

for col in ['ALUNNI', 'ALUNNICITTADINANZAITALIANA', 'ALUNNICITTADINANZANONITALIANA',
            'ALUNNICITTADINANZANONITALIANAPAESIUE', 'ALUNNICITTADINANZANONITALIANAPAESINONUE']:
    cit[col] = pd.to_numeric(cit[col].replace('', '0'))
for col in ['CLASSI', 'ALUNNIMASCHI', 'ALUNNIFEMMINE']:
    cla[col] = pd.to_numeric(cla[col].replace('', '0'))
cla['ALUNNI_CLASSI'] = cla['ALUNNIMASCHI'] + cla['ALUNNIFEMMINE']
cit['QUOTA'] = cit['ALUNNICITTADINANZANONITALIANA'] / cit['ALUNNI']
cit['SOPRA_30'] = 10 * cit['ALUNNICITTADINANZANONITALIANA'] > 3 * cit['ALUNNI']

# Anagrafe ridotta (primo codice, come in analyze.py) da unire alle righe grezze
ANA_COLS = ['CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'CODICEISTITUTORIFERIMENTO', 'DESCRIZIONECOMUNE',
            'PROVINCIA', 'DESCRIZIONECARATTERISTICASCUOLA', 'DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA', 'fonte']
ana_1 = ana.drop_duplicates('CODICESCUOLA', keep='first')[ANA_COLS]
citx = cit.merge(ana_1, on='CODICESCUOLA', how='left')

len(cit), len(cla), len(ana)

(134784, 131283, 63269)

In [51]:
def mostra(codice):
    """Tutte le righe grezze di un plesso: anagrafe, cittadinanza, classi."""
    print('--- ANAGRAFE')
    display(ana[ana['CODICESCUOLA'].eq(codice)].T)
    print('--- CITTADINANZA')
    display(cit[cit['CODICESCUOLA'].eq(codice)].sort_values(['ORDINESCUOLA', 'ANNOCORSO']))
    print('--- CLASSI/STUDENTI')
    display(cla[cla['CODICESCUOLA'].eq(codice)].sort_values(['ORDINESCUOLA', 'ANNOCORSOCLASSE']))

In [52]:
mostra('GREE82601G')

--- ANAGRAFE

                                                                 30
gestione                                                    statale
ANNOSCOLASTICO                                               202425
AREAGEOGRAFICA                                               CENTRO
REGIONE                                                     TOSCANA
PROVINCIA                                                  GROSSETO
CODICEISTITUTORIFERIMENTO                                GRIC82600D
DENOMINAZIONEISTITUTORIFERIMENTO                      IC GROSSETO 6
CODICESCUOLA                                             GREE82601G
DENOMINAZIONESCUOLA                            ISTIA - "C.SABATINI"
INDIRIZZOSCUOLA                                 PIAZZA S.SEBASTIANO
CAPSCUOLA                                                     58010
CODICECOMUNESCUOLA                                             E202
DESCRIZIONECOMUNE                                          GROSSETO
DESCRIZIONECARATTERISTICASCUOLA                             NORMALE
DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA           SCUOLA PRIMARIA
INDICAZIONESEDEDIRETTIVO                                         NO
INDICAZIONESEDEOMNICOMPRENSIVO                      Non Disponibile
INDIRIZZOEMAILSCUOLA                       GRIC82600D@istruzione.it
INDIRIZZOPECSCUOLA                                  Non Disponibile
SITOWEBSCUOLA                                    www.icgrosseto6.it
SEDESCOLASTICA                                                   SI
fonte                                                      standard

--- CITTADINANZA

      gestione ANNOSCOLASTICO CODICESCUOLA     ORDINESCUOLA ANNOCORSO  ALUNNI  ALUNNICITTADINANZAITALIANA  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA  SOPRA_30
65052  statale         202425   GREE82601G  SCUOLA PRIMARIA         1      26                          23                              3                                     0                                        3  0.115385     False
61101  statale         202425   GREE82601G  SCUOLA PRIMARIA         2      18                          18                              0                                     0                                        0  0.000000     False
60562  statale         202425   GREE82601G  SCUOLA PRIMARIA         3      21                          20                              1                                     0                                        1  0.047619     False
62919  statale         202425   GREE82601G  SCUOLA PRIMARIA         4      22                          19                              3                                     0                                        3  0.136364     False
62191  statale         202425   GREE82601G  SCUOLA PRIMARIA         5      15                          14                              1                                     1                                        0  0.066667     False

--- CLASSI/STUDENTI

      gestione ANNOSCOLASTICO CODICESCUOLA     ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
91285  statale         202425   GREE82601G  SCUOLA PRIMARIA               1       1            15             11             26
62872  statale         202425   GREE82601G  SCUOLA PRIMARIA               2       1            10              8             18
42487  statale         202425   GREE82601G  SCUOLA PRIMARIA               3       1            16              5             21
19555  statale         202425   GREE82601G  SCUOLA PRIMARIA               4       1            16              6             22
0      statale         202425   GREE82601G  SCUOLA PRIMARIA               5       1             9              6             15

## 1. Unità = anno di corso, non classe

Il flusso classi dà solo il **numero** di classi per anno di corso, non la composizione di ciascuna. Qui si vede quante sezioni vengono sommate nelle unità sopra soglia.

In [75]:
chiave_cit = ['gestione', 'CODICESCUOLA', 'ORDINESCUOLA', 'ANNOCORSO']
uc = cit.merge(
    cla.rename(columns={'ANNOCORSOCLASSE': 'ANNOCORSO'})[chiave_cit + ['CLASSI', 'ALUNNI_CLASSI']],
    on=chiave_cit, how='left',
)

In [77]:
chiave_cit = ['gestione', 'CODICESCUOLA', 'ORDINESCUOLA', 'ANNOCORSO']
uc = cit.merge(
    cla.rename(columns={'ANNOCORSOCLASSE': 'ANNOCORSO'})[chiave_cit + ['CLASSI', 'ALUNNI_CLASSI']],
    on=chiave_cit, how='left',
)
uc['ALUNNI_PER_CLASSE'] = uc['ALUNNI'] / uc['CLASSI']

# Distribuzione del numero di classi per unità, separando unità sopra/sotto soglia
display(pd.crosstab(pd.cut(uc['CLASSI'], [0, 1, 2, 4, 8, 12, 100]), uc['SOPRA_30'], margins=True))

# Unità con molte classi appena sotto soglia (25-30%): qui è probabile che qualche sezione sia sopra il 30%
uc[(uc['CLASSI'] >= 4) & uc['QUOTA'].between(0.25, 0.30)].sort_values('CLASSI', ascending=False).head(20)

SOPRA_30    False   True     All
CLASSI
(0, 1]      49188   5583   54771
(1, 2]      27187   3760   30947
(2, 4]      21703   2654   24357
(4, 8]      13861    916   14777
(8, 12]      4014     93    4107
(12, 100]     906      9     915
All        116859  13015  129874

,gestione,ANNOSCOLASTICO,CODICESCUOLA,ORDINESCUOLA,ANNOCORSO,ALUNNI,ALUNNICITTADINANZAITALIANA,ALUNNICITTADINANZANONITALIANA,ALUNNICITTADINANZANONITALIANAPAESIUE,ALUNNICITTADINANZANONITALIANAPAESINONUE,QUOTA,SOPRA_30,CLASSI,ALUNNI_CLASSI,ALUNNI_PER_CLASSE
7070,statale,202425,TOTF14000A,SCUOLA SECONDARIA II GRADO,3,305,227,78,32,46,0.255738,False,15.0,305.0,20.333333
76772,statale,202425,PCTD003011,SCUOLA SECONDARIA II GRADO,1,362,258,104,13,91,0.287293,False,15.0,362.0,24.133333
106797,statale,202425,MORC08000G,SCUOLA SECONDARIA II GRADO,1,346,245,101,5,96,0.291908,False,15.0,346.0,23.066667
14962,statale,202425,PCMM00200Q,SCUOLA SECONDARIA I GRADO,3,328,235,93,9,84,0.283537,False,15.0,328.0,21.866667
68624,statale,202425,PCTF00601P,SCUOLA SECONDARIA II GRADO,1,354,260,94,7,87,0.265537,False,14.0,354.0,25.285714
57136,statale,202425,MITN03000E,SCUOLA SECONDARIA II GRADO,1,318,228,90,6,84,0.283019,False,14.0,318.0,22.714286
80388,statale,202425,VRTF03000V,SCUOLA SECONDARIA II GRADO,1,354,254,100,27,73,0.282486,False,14.0,354.0,25.285714
89659,statale,202425,MITF01701D,SCUOLA SECONDARIA II GRADO,1,320,231,89,9,80,0.278125,False,14.0,320.0,22.857143
95520,statale,202425,PCMM00400B,SCUOLA SECONDARIA I GRADO,1,324,239,85,8,77,0.262346,False,14.0,324.0,23.142857
71297,statale,202425,RMTF009013,SCUOLA SECONDARIA II GRADO,1,291,211,80,21,59,0.274914,False,13.0,291.0,22.384615
45422,statale,202425,BSRI03201L,SCUOLA SECONDARIA II GRADO,2,318,225,93,6,87,0.292453,False,13.0,318.0,24.461538
92821,statale,202425,FIRH020009,SCUOLA SECONDARIA II GRADO,1,289,211,78,6,72,0.269896,False,13.0,289.0,22.230769
72022,statale,202425,RMTF009013,SCUOLA SECONDARIA II GRADO,2,289,213,76,24,52,0.262976,False,13.0,289.0,22.230769
71066,statale,202425,POPS002013,SCUOLA SECONDARIA II GRADO,1,288,215,73,2,71,0.253472,False,12.0,288.0,24.000000
85743,statale,202425,POPS02000G,SCUOLA SECONDARIA II GRADO,1,320,234,86,2,84,0.268750,False,12.0,320.0,26.666667
72251,statale,202425,BSTD15000L,SCUOLA SECONDARIA II GRADO,2,240,174,66,11,55,0.275000,False,12.0,240.0,20.000000
95210,statale,202425,MIMM8CW014,SCUOLA SECONDARIA I GRADO,1,231,170,61,3,58,0.264069,False,12.0,231.0,19.250000
56257,statale,202425,MITN03000E,SCUOLA SECONDARIA II GRADO,2,261,190,71,5,66,0.272031,False,12.0,261.0,21.750000
70277,statale,202425,RMTF009013,SCUOLA SECONDARIA II GRADO,3,267,191,76,22,54,0.284644,False,12.0,267.0,22.250000
83915,statale,202425,MIMM8CW014,SCUOLA SECONDARIA I GRADO,2,253,178,75,7,68,0.296443,False,12.0,253.0,21.083333

In [16]:
mostra('MOPS030002')

--- ANAGRAFE

                                                                  21495
gestione                                                        statale
ANNOSCOLASTICO                                                   202425
AREAGEOGRAFICA                                                 NORD EST
REGIONE                                                  EMILIA ROMAGNA
PROVINCIA                                                        MODENA
CODICEISTITUTORIFERIMENTO                                    MOPS030002
DENOMINAZIONEISTITUTORIFERIMENTO                         MANFREDO FANTI
CODICESCUOLA                                                 MOPS030002
DENOMINAZIONESCUOLA                                      MANFREDO FANTI
INDIRIZZOSCUOLA                                         VIALE PERUZZI 7
CAPSCUOLA                                                         41012
CODICECOMUNESCUOLA                                                 B819
DESCRIZIONECOMUNE                                                 CARPI
DESCRIZIONECARATTERISTICASCUOLA                                 NORMALE
DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA             LICEO SCIENTIFICO
INDICAZIONESEDEDIRETTIVO                                             SI
INDICAZIONESEDEOMNICOMPRENSIVO                          Non Disponibile
INDIRIZZOEMAILSCUOLA                           MOPS030002@istruzione.it
INDIRIZZOPECSCUOLA                         mops030002@pec.istruzione.it
SITOWEBSCUOLA                                     www.liceofanti.edu.it
SEDESCOLASTICA                                                       SI
fonte                                                          standard

--- CITTADINANZA

      gestione ANNOSCOLASTICO CODICESCUOLA                ORDINESCUOLA ANNOCORSO  ALUNNI  ALUNNICITTADINANZAITALIANA  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA  SOPRA_30
74111  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO         1     514                         474                             40                                     9                                       31  0.077821     False
73163  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO         2     424                         388                             36                                     5                                       31  0.084906     False
65252  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO         3     449                         415                             34                                     7                                       27  0.075724     False
64292  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO         4     386                         362                             24                                     4                                       20  0.062176     False
60348  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO         5     340                         323                             17                                     1                                       16  0.050000     False

--- CLASSI/STUDENTI

       gestione ANNOSCOLASTICO CODICESCUOLA                ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
51843   statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO               1      19           152            362            514
77512   statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO               2      18           123            301            424
108369  statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO               3      19           163            286            449
25499   statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO               4      17           136            250            386
36330   statale         202425   MOPS030002  SCUOLA SECONDARIA II GRADO               5      15           124            216            340

## 2. IC Polla (SA) – `SAIC872009`: possibile errore di codifica della cittadinanza

Da controllare: la ripartizione UE/non UE (es. una comunità specifica) e il confronto con gli istituti vicini della stessa provincia.

In [78]:
plessi_polla = ana.loc[ana['CODICEISTITUTORIFERIMENTO'].eq('SAIC872009'), 'CODICESCUOLA'].unique()
display(ana[ana['CODICESCUOLA'].isin(plessi_polla)][
    ['CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'DESCRIZIONECOMUNE', 'INDIRIZZOSCUOLA',
     'DESCRIZIONECARATTERISTICASCUOLA', 'DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA', 'fonte']])
cit[cit['CODICESCUOLA'].isin(plessi_polla)].sort_values(['CODICESCUOLA', 'ANNOCORSO'])

      CODICESCUOLA       DENOMINAZIONESCUOLA DESCRIZIONECOMUNE         INDIRIZZOSCUOLA DESCRIZIONECARATTERISTICASCUOLA DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA     fonte
33523   SAAA87205A  SCUOLA INFANZIA CAGGIANO          CAGGIANO         VIA EX CONVENTO                         NORMALE                           SCUOLA INFANZIA  standard
35453   SAAA872016              "CAPPUCCINI"             POLLA          VIA CAPPUCCINI                         NORMALE                           SCUOLA INFANZIA  standard
36229   SAEE87206L              AULETTA CAP.           AULETTA      VIA LARGO CAPPELLI                         NORMALE                           SCUOLA PRIMARIA  standard
36801   SAAA872049              PERTOSA CAP.           PERTOSA         VIA EUROPA N. 2                         NORMALE                           SCUOLA INFANZIA  standard
37412   SAAA872038           POLLA CAPOLUOGO             POLLA         VIA A. ISOLDI 1                         NORMALE                           SCUOLA INFANZIA  standard
38198   SAEE87202C                 S. PIETRO             POLLA           VIA GARIBALDI                         NORMALE                           SCUOLA PRIMARIA  standard
39310   SAEE87201B            POLLA CAP.P.P.             POLLA       VIA A. ISOLDI N.1                         NORMALE                           SCUOLA PRIMARIA  standard
39555   SAEE87204E              CAGGIANO CAP          CAGGIANO  VIA CAFARO FORTUNATO 1                         NORMALE                           SCUOLA PRIMARIA  standard
40126   SAEE87203D              PERTOSA CAP.           PERTOSA              VIA EUROPA                         NORMALE                           SCUOLA PRIMARIA  standard
44461   SAEE87205G            SALVITELLE CAP        SALVITELLE     LARGO S. SEBASTIANO                         NORMALE                           SCUOLA PRIMARIA  standard
45116   SAIC872009              I.O.C. POLLA             POLLA         VIA A. ISOLDI 1                         NORMALE                      ISTITUTO COMPRENSIVO  standard
47135   SAMM87201A       POLLA "E.DE AMICIS"             POLLA          VIA ANNIA N. 1                         NORMALE                        SCUOLA PRIMO GRADO  standard
47793   SAAA87206B                   AULETTA           AULETTA         VIA PROVINCIALE                         NORMALE                           SCUOLA INFANZIA  standard
48483   SAMM87203C                   AULETTA           AULETTA      VIA LARGO CAPPELLI                         NORMALE                        SCUOLA PRIMO GRADO  standard
49124   SAMM87202B                  CAGGIANO          CAGGIANO  VIA CAFARO FORTUNATO 3                         NORMALE                        SCUOLA PRIMO GRADO  standard

      gestione ANNOSCOLASTICO CODICESCUOLA               ORDINESCUOLA ANNOCORSO  ALUNNI  ALUNNICITTADINANZAITALIANA  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA  SOPRA_30
40443  statale         202425   SAEE87201B            SCUOLA PRIMARIA         1      17                           0                             17                                     1                                       16  1.000000      True
41165  statale         202425   SAEE87201B            SCUOLA PRIMARIA         2      14                           0                             14                                     0                                       14  1.000000      True
44834  statale         202425   SAEE87201B            SCUOLA PRIMARIA         3      18                           0                             18                                     0                                       18  1.000000      True
45572  statale         202425   SAEE87201B            SCUOLA PRIMARIA         4      11                           0                             11                                     0                                       11  1.000000      True
43495  statale         202425   SAEE87201B            SCUOLA PRIMARIA         5      24                          21                              3                                     1                                        2  0.125000     False
44230  statale         202425   SAEE87202C            SCUOLA PRIMARIA         1      21                           1                             20                                     0                                       20  0.952381      True
23630  statale         202425   SAEE87202C            SCUOLA PRIMARIA         2      16                           0                             16                                     0                                       16  1.000000      True
24392  statale         202425   SAEE87202C            SCUOLA PRIMARIA         3      13                           0                             13                                     0                                       13  1.000000      True
21872  statale         202425   SAEE87202C            SCUOLA PRIMARIA         4      16                           0                             16                                     0                                       16  1.000000      True
6483   statale         202425   SAEE87202C            SCUOLA PRIMARIA         5      25                          24                              1                                     0                                        1  0.040000     False
4077   statale         202425   SAEE87203D            SCUOLA PRIMARIA         1       4                           0                              4                                     0                                        4  1.000000      True
4837   statale         202425   SAEE87203D            SCUOLA PRIMARIA         2       6                           0                              6                                     0                                        6  1.000000      True
8738   statale         202425   SAEE87203D            SCUOLA PRIMARIA         3       3                           0                              3                                     0                                        3  1.000000      True
9695   statale         202425   SAEE87203D            SCUOLA PRIMARIA         4       3                           0                              3                                     0                                        3  1.000000      True
7336   statale         202425   SAEE87203D            SCUOLA PRIMARIA         5       1                           1                              0                                     0                                        0  0.000000     False
52651  statale         202425   SAEE87204E            SCUOLA PRIMARIA         1      20                           0                             20                                     1                                       19  1.000000      True
56408  statale         202425   SAEE87204E            SCUOLA PRIMARIA         2      10                           0                             10                                     0                                       10  1.000000      True
56934  statale         202425   SAEE87204E            SCUOLA PRIMARIA         3      10                           0                             10                                     0                                       10  1.000000      True
54678  statale         202425   SAEE87204E            SCUOLA PRIMARIA         4      21                           1                             20                                     0                                       20  0.952381      True
55376  statale         202425   SAEE87204E            SCUOLA PRIMARIA         5      22                          20                              2                                     0                                        2  0.090909     False
59179  statale         202425   SAEE87206L            SCUOLA PRIMARIA         1      14                           0                             14                                     0                                       14  1.000000      True
60103  statale         202425   SAEE87206L            SCUOLA PRIMARIA         2      11                           1                             10                                     0                                       10  0.909091      True
57815  statale         202425   SAEE87206L            SCUOLA PRIMARIA         3      13                           1                             12                                     0                                       12  0.923077      True
58516  statale         202425   SAEE87206L            SCUOLA PRIMARIA         4      28                           1                             27                                     0                                       27  0.964286      True
38193  statale         202425   SAEE87206L            SCUOLA PRIMARIA         5      13                          11                              2                                     2                                        0  0.153846     False
53874  statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO         1      62                           0                             62                                     0                                       62  1.000000      True
54613  statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO         2      45                           0                             45                                     1                                       44  1.000000      True
52495  statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO         3      68                          10                             58                                     1                                       57  0.852941      True
53251  statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO         1      20                           0                             20                                     0                                       20  1.000000      True
56958  statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO         2      24                           0                             24                                     0                                       24  1.000000      True
57721  statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO         3      29                          28                              1                                     0                                        1  0.034483     False
55202  statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO         1      16                           0                             16                                     1                                       15  1.000000      True
55986  statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO         2      17                           0                             17                                     2                                       15  1.000000      True
56940  statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO         3      14                          13                              1                                     0                                        1  0.071429     False

In [79]:
# Il flusso classi è coerente con quello per cittadinanza?
cla[cla['CODICESCUOLA'].isin(plessi_polla)].sort_values(['CODICESCUOLA', 'ANNOCORSOCLASSE'])

       gestione ANNOSCOLASTICO CODICESCUOLA               ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
97816   statale         202425   SAEE87201B            SCUOLA PRIMARIA               1       1            10              7             17
58501   statale         202425   SAEE87201B            SCUOLA PRIMARIA               2       1             8              6             14
52155   statale         202425   SAEE87201B            SCUOLA PRIMARIA               3       1             7             11             18
8532    statale         202425   SAEE87201B            SCUOLA PRIMARIA               4       1             4              7             11
95482   statale         202425   SAEE87201B            SCUOLA PRIMARIA               5       1            12             12             24
57162   statale         202425   SAEE87202C            SCUOLA PRIMARIA               1       1            12              9             21
71459   statale         202425   SAEE87202C            SCUOLA PRIMARIA               2       1             9              7             16
31880   statale         202425   SAEE87202C            SCUOLA PRIMARIA               3       1             6              7             13
66392   statale         202425   SAEE87202C            SCUOLA PRIMARIA               4       1             5             11             16
97744   statale         202425   SAEE87202C            SCUOLA PRIMARIA               5       1            16              9             25
83324   statale         202425   SAEE87203D            SCUOLA PRIMARIA               1       1             2              2              4
42376   statale         202425   SAEE87203D            SCUOLA PRIMARIA               2       1             2              4              6
40301   statale         202425   SAEE87203D            SCUOLA PRIMARIA               3       1             2              1              3
58828   statale         202425   SAEE87203D            SCUOLA PRIMARIA               4       1             2              1              3
87120   statale         202425   SAEE87203D            SCUOLA PRIMARIA               5       1             1              0              1
82592   statale         202425   SAEE87204E            SCUOLA PRIMARIA               1       1            10             10             20
13473   statale         202425   SAEE87204E            SCUOLA PRIMARIA               2       1             7              3             10
114764  statale         202425   SAEE87204E            SCUOLA PRIMARIA               3       1             8              2             10
64124   statale         202425   SAEE87204E            SCUOLA PRIMARIA               4       1            11             10             21
58616   statale         202425   SAEE87204E            SCUOLA PRIMARIA               5       1            11             11             22
97148   statale         202425   SAEE87206L            SCUOLA PRIMARIA               1       1             8              6             14
72182   statale         202425   SAEE87206L            SCUOLA PRIMARIA               2       1             4              7             11
54434   statale         202425   SAEE87206L            SCUOLA PRIMARIA               3       1             6              7             13
13846   statale         202425   SAEE87206L            SCUOLA PRIMARIA               4       2            16             12             28
54800   statale         202425   SAEE87206L            SCUOLA PRIMARIA               5       1             9              4             13
73063   statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO               1       3            30             32             62
40446   statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO               2       2            14             31             45
31574   statale         202425   SAMM87201A  SCUOLA SECONDARIA I GRADO               3       3            37             31             68
36901   statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO               1       1            11              9             20
70190   statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO               2       1            13             11             24
17781   statale         202425   SAMM87202B  SCUOLA SECONDARIA I GRADO               3       2            14             15             29
53478   statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO               1       1             5             11             16
110519  statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO               2       1            12              5             17
61465   statale         202425   SAMM87203C  SCUOLA SECONDARIA I GRADO               3       1             5              9             14

In [80]:
# Quota di non italiani per istituto in provincia di Salerno: Polla è un outlier isolato?
ist_sa = (
    citx[citx['PROVINCIA'].eq('SALERNO')]
    .groupby(['CODICEISTITUTORIFERIMENTO', 'DESCRIZIONECOMUNE'])[
        ['ALUNNI', 'ALUNNICITTADINANZANONITALIANA',
         'ALUNNICITTADINANZANONITALIANAPAESIUE', 'ALUNNICITTADINANZANONITALIANAPAESINONUE']]
    .sum()
)
ist_sa['QUOTA'] = ist_sa['ALUNNICITTADINANZANONITALIANA'] / ist_sa['ALUNNI']
ist_sa.sort_values('QUOTA', ascending=False).head(15)

                                                      ALUNNI  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA
CODICEISTITUTORIFERIMENTO DESCRIZIONECOMUNE
SAIC872009                PERTOSA                         17                             16                                     0                                       16  0.941176
                          POLLA                          350                            294                                     4                                      290  0.840000
                          AULETTA                        126                             99                                     5                                       94  0.785714
SAIC8AH00L                ROSCIGNO                        10                              7                                     0                                        7  0.700000
SAIC872009                CAGGIANO                       156                            107                                     1                                      106  0.685897
SAIC830007                BELLOSGUARDO                    18                              9                                     0                                        9  0.500000
SAIC8BL004                MAGLIANO VETERE                 11                              5                                     1                                        4  0.454545
SAIC8BM00X                CORLETO MONFORTE                57                             17                                     7                                       10  0.298246
                          SANT'ANGELO A FASANELLA         17                              5                                     5                                        0  0.294118
SAIC8A900C                SAN MARZANO SUL SARNO          871                            247                                    24                                      223  0.283582
SAIC81900C                EBOLI                          942                            244                                    75                                      169  0.259023
SAIC83900N                BATTIPAGLIA                    729                            171                                    23                                      148  0.234568
SAIC830007                PIAGGINE                        64                             14                                     0                                       14  0.218750
SATN02000X                MONTESANO SULLA MARCELLANA     124                             24                                     5                                       19  0.193548
SAIC8BM00X                CONTRONE                        52                             10                                     5                                        5  0.192308

## 3. Corsi serali, CPIA, carceri, ospedali

L'anagrafe ha il campo `DESCRIZIONECARATTERISTICASCUOLA` (PERCORSO II LIVELLO = serale, SPEC. PER CARCERARI, CPIA, C/O IST. OSPEDALIERO, …), più affidabile della ricerca nel nome.

In [81]:
car = citx.groupby('DESCRIZIONECARATTERISTICASCUOLA').agg(
    unita=('ALUNNI', 'size'),
    unita_sopra_30=('SOPRA_30', 'sum'),
    alunni=('ALUNNI', 'sum'),
    non_italiani=('ALUNNICITTADINANZANONITALIANA', 'sum'),
)
car['quota_non_italiani'] = car['non_italiani'] / car['alunni']
car['pct_unita_sopra_30'] = car['unita_sopra_30'] / car['unita']
car.sort_values('unita', ascending=False)

                                  unita  unita_sopra_30   alunni  non_italiani  quota_non_italiani  pct_unita_sopra_30
DESCRIZIONECARATTERISTICASCUOLA
NORMALE                          113665           12213  5980898        719502            0.120300            0.107447
PERCORSO II LIVELLO                3257             739    76783         14451            0.188206            0.226896
ANNESSO A CONVITTO                  586              25    36036          2361            0.065518            0.042662
SPEC. PER CARCERARI                 519             133     6965          1247            0.179038            0.256262
CONVITTO ANNESSO                    473               4    29182          1865            0.063909            0.008457
ISOLANO                             385              19    11658           703            0.060302            0.049351
DI MONTAGNA                         354              71     2632           484            0.183891            0.200565
SCUOLA ANNESSA                      224               2    17337          1443            0.083232            0.008929
SLOVENO                             202              12     3154           188            0.059607            0.059406
ANN. A EDUCANDATO                    78               3     6220           367            0.059003            0.038462
PER SORDOMUTI                        18               1      669            89            0.133034            0.055556
SPERIMENTALE PER DM                  12               3      680           179            0.263235            0.250000
PER CIECHI                            9               0      376            11            0.029255            0.000000
SPEC. PER SORDOMUTI                   5               0       80             5            0.062500            0.000000
ANN. A ISTITUTO ARTE                  3               0       18             2            0.111111            0.000000
C/O IST. OSPEDALIERO                  2               2        3             2            0.666667            1.000000
SPECIALE PER CIECHI                   1               0       26             5            0.192308            0.000000

In [82]:
# Nomi con SERALE/CPIA/SIRIO che però l'anagrafe classifica come NORMALE (e viceversa)
nome_adulti = citx['DENOMINAZIONESCUOLA'].str.contains(r'SERALE|CPIA|C\.P\.I\.A|SIRIO|ADULTI|CARCER', case=False, na=False)
pd.crosstab(citx['DESCRIZIONECARATTERISTICASCUOLA'], nome_adulti)

DENOMINAZIONESCUOLA               False  True
DESCRIZIONECARATTERISTICASCUOLA
ANN. A EDUCANDATO                    78      0
ANN. A ISTITUTO ARTE                  3      0
ANNESSO A CONVITTO                  586      0
C/O IST. OSPEDALIERO                  2      0
CONVITTO ANNESSO                    473      0
DI MONTAGNA                         354      0
ISOLANO                             385      0
NORMALE                          113650     15
PER CIECHI                            9      0
PER SORDOMUTI                        18      0
PERCORSO II LIVELLO                 640   2617
SCUOLA ANNESSA                      224      0
SLOVENO                             202      0
SPEC. PER CARCERARI                 361    158
SPEC. PER SORDOMUTI                   5      0
SPECIALE PER CIECHI                   1      0
SPERIMENTALE PER DM                  12      0

In [22]:
# Classi con più di 35 alunni: quasi certamente iscritti a percorsi per adulti, non classi reali
uc_x = uc.merge(ana_1, on='CODICESCUOLA', how='left')
uc_x[uc_x['ALUNNI_PER_CLASSE'] > 35].sort_values('ALUNNI_PER_CLASSE', ascending=False)[
    ['gestione', 'CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'DESCRIZIONECARATTERISTICASCUOLA',
     'ANNOCORSO', 'ALUNNI', 'CLASSI', 'ALUNNI_PER_CLASSE', 'QUOTA']]

       gestione CODICESCUOLA                       DENOMINAZIONESCUOLA DESCRIZIONECARATTERISTICASCUOLA ANNOCORSO  ALUNNI  CLASSI  ALUNNI_PER_CLASSE     QUOTA
53095   statale   SATL046502              ITG DI PALO SERALE - SALERNO             PERCORSO II LIVELLO         4     101     1.0              101.0  0.148515
76661   statale   CTTD220503      IIS "ENRICO DE NICOLA" - CORSO SIRIO             PERCORSO II LIVELLO         2      90     1.0               90.0  0.066667
28756   statale   BNRC02650N               I.P. "A. MORO" CORSO SERALE             PERCORSO II LIVELLO         4      73     1.0               73.0  0.027397
54920   statale   PATN010505          IST.T. TURISMO MARCO POLO SERALE             PERCORSO II LIVELLO         1      71     1.0               71.0  0.084507
23174   statale   CTTF030517                                CANNIZZARO             PERCORSO II LIVELLO         3     136     2.0               68.0  0.000000
...         ...          ...                                       ...                             ...       ...     ...     ...                ...       ...
36988   statale   RNRC006519                       "L. EINAUDI" SERALE             PERCORSO II LIVELLO         4      36     1.0               36.0  0.250000
49452   statale   CSRI06351E         SERALE IPSIA RISTORAZ. TREBISACCE             PERCORSO II LIVELLO         2      71     2.0               35.5  0.225352
69383   statale   BGRH02050P  ISTR. PROF. SERALE - ENOGASTR. OSP. ALB.             PERCORSO II LIVELLO         4      71     2.0               35.5  0.295775
108437  statale   PIRI020512                           IPSIA PACINOTTI             PERCORSO II LIVELLO         4      71     2.0               35.5  0.225352
49775   statale   CTTD03401V                   ITC DE FELICE GIUFFRIDA                         NORMALE         1      71     2.0               35.5  0.225352

[113 rows x 9 columns]

In [23]:
# CPIA classificato come paritaria
mostra('LT1MZZ500E')

--- ANAGRAFE

                                                                         59242
gestione                                                             paritaria
ANNOSCOLASTICO                                                          202425
AREAGEOGRAFICA                                                          CENTRO
REGIONE                                                                  LAZIO
PROVINCIA                                                               LATINA
CODICEISTITUTORIFERIMENTO                                                  NaN
DENOMINAZIONEISTITUTORIFERIMENTO                                           NaN
CODICESCUOLA                                                        LT1MZZ500E
DENOMINAZIONESCUOLA                                            C.P.I.A. Lenola
INDIRIZZOSCUOLA                                             VIA SANTA CROCE 16
CAPSCUOLA                                                                04025
CODICECOMUNESCUOLA                                                        E527
DESCRIZIONECOMUNE                                                       LENOLA
DESCRIZIONECARATTERISTICASCUOLA                                            NaN
DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA  SCUOLA SEC. PRIMO GRADO NON STATALE
INDICAZIONESEDEDIRETTIVO                                                   NaN
INDICAZIONESEDEOMNICOMPRENSIVO                                             NaN
INDIRIZZOEMAILSCUOLA                         associazioneatenalenola@gmail.com
INDIRIZZOPECSCUOLA                              associazioneatenalenola@pec.it
SITOWEBSCUOLA                                                www.cpialenola.it
SEDESCOLASTICA                                                             NaN
fonte                                                                 standard

--- CITTADINANZA

         gestione ANNOSCOLASTICO CODICESCUOLA               ORDINESCUOLA ANNOCORSO  ALUNNI  ALUNNICITTADINANZAITALIANA  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA  SOPRA_30
121881  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO         1      30                           0                             30                                     0                                       30  1.000000      True
121096  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO         2      19                           6                             13                                     0                                       13  0.684211      True
126868  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO         3      43                           0                             43                                     0                                       43  1.000000      True

--- CLASSI/STUDENTI

         gestione ANNOSCOLASTICO CODICESCUOLA               ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
126969  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO               1       1            29              1             30
125982  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO               2       1            16              3             19
125229  paritaria         202425   LT1MZZ500E  SCUOLA SECONDARIA I GRADO               3       2            41              2             43

## 4. Unità molto piccole (N ≤ 5)

In [24]:
piccole = citx[citx['SOPRA_30'] & citx['ALUNNI'].le(5)]
display(pd.crosstab(piccole['ALUNNI'], piccole['ALUNNICITTADINANZANONITALIANA'], margins=True))
display(piccole.groupby(['gestione', 'ORDINESCUOLA', 'DESCRIZIONECARATTERISTICASCUOLA']).size().sort_values(ascending=False))
piccole.sample(15, random_state=0)

ALUNNICITTADINANZANONITALIANA    1    2   3   4  5   All
ALUNNI
1                              106    0   0   0  0   106
2                              221   52   0   0  0   273
3                              290   90  14   0  0   394
4                                0  112  30  13  0   155
5                                0  148  49  10  7   214
All                            617  402  93  23  7  1142

gestione  ORDINESCUOLA                DESCRIZIONECARATTERISTICASCUOLA
statale   SCUOLA PRIMARIA             NORMALE                            748
          SCUOLA SECONDARIA I GRADO   NORMALE                             82
          SCUOLA PRIMARIA             DI MONTAGNA                         49
          SCUOLA SECONDARIA II GRADO  PERCORSO II LIVELLO                 43
                                      SPEC. PER CARCERARI                 39
          SCUOLA PRIMARIA             ISOLANO                             13
                                      SLOVENO                              5
          SCUOLA SECONDARIA I GRADO   C/O IST. OSPEDALIERO                 2
                                      ISOLANO                              2
          SCUOLA PRIMARIA             ANNESSO A CONVITTO                   1
          SCUOLA SECONDARIA I GRADO   SLOVENO                              1
          SCUOLA SECONDARIA II GRADO  SLOVENO                              1
dtype: int64

,gestione,ANNOSCOLASTICO,CODICESCUOLA,ORDINESCUOLA,ANNOCORSO,ALUNNI,ALUNNICITTADINANZAITALIANA,ALUNNICITTADINANZANONITALIANA,ALUNNICITTADINANZANONITALIANAPAESIUE,ALUNNICITTADINANZANONITALIANAPAESINONUE,QUOTA,SOPRA_30,DENOMINAZIONESCUOLA,CODICEISTITUTORIFERIMENTO,DESCRIZIONECOMUNE,PROVINCIA,DESCRIZIONECARATTERISTICASCUOLA,DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA,fonte
13904,statale,202425,MCTF004507,SCUOLA SECONDARIA II GRADO,1,2,1,1,0,1,0.500000,True,I.T.INDUSTRIALE RECANATI (CORSO SERALE),MCIS00400A,RECANATI,MACERATA,PERCORSO II LIVELLO,ISTITUTO TECNICO INDUSTRIALE,standard
80263,statale,202425,CSMM851025,SCUOLA SECONDARIA I GRADO,2,2,1,1,0,1,0.500000,True,SM FIGLINE V.,CSIC851003,FIGLINE VEGLIATURO,COSENZA,NORMALE,SCUOLA PRIMO GRADO,standard
46933,statale,202425,APEE82203R,SCUOLA PRIMARIA,5,3,2,1,0,1,0.333333,True,PRIMARIA LAPEDONA,APIC82200L,LAPEDONA,FERMO,NORMALE,SCUOLA PRIMARIA,standard
121321,paritaria,202425,SATDBD5007,SCUOLA SECONDARIA II GRADO,4,1,0,1,0,1,1.000000,True,"""CAMPUS"" IT Sett. Econ. Ind. AFM",NaN,NOCERA INFERIORE,SALERNO,NaN,SCUOLA SEC. SECONDO GRADO NON STATALE,standard
27655,statale,202425,VBEE814054,SCUOLA PRIMARIA,2,2,1,1,0,1,0.500000,True,SCUOLA ELEMENTARE DI TORCHIEDO,VBIC81400T,VERBANIA,VERBANO-CUSIO-OSSOLA,NORMALE,SCUOLA PRIMARIA,standard
55350,statale,202425,APEE80906D,SCUOLA PRIMARIA,1,3,2,1,1,0,0.333333,True,ROTELLA,APIC809006,ROTELLA,ASCOLI PICENO,NORMALE,SCUOLA PRIMARIA,standard
1858,statale,202425,SAEE87707R,SCUOLA PRIMARIA,5,4,2,2,1,1,0.500000,True,GIFFONI SEI CASALI CAPITIGNANO,SAIC87700C,GIFFONI SEI CASALI,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
42771,statale,202425,CSEE864017,SCUOLA PRIMARIA,2,4,2,2,0,2,0.500000,True,SCIGLIANO IC,CSIC864005,SCIGLIANO,COSENZA,NORMALE,SCUOLA PRIMARIA,standard
25757,statale,202425,ISEE81203R,SCUOLA PRIMARIA,4,3,2,1,0,1,0.333333,True,CAPRACOTTA CAPOLUOGO,ISIC81200L,CAPRACOTTA,ISERNIA,NORMALE,SCUOLA PRIMARIA,standard
52026,statale,202425,AREE814022,SCUOLA PRIMARIA,3,2,1,1,0,1,0.500000,True,"""FRATELLI BIMBI""",ARIC81400V,BADIA TEDALDA,AREZZO,NORMALE,SCUOLA PRIMARIA,standard
34322,statale,202425,ALEE810039,SCUOLA PRIMARIA,4,3,2,1,0,1,0.333333,True,"""G.UNGARETTI - MONTECHIARO",ALIC810005,MONTECHIARO D'ACQUI,ALESSANDRIA,NORMALE,SCUOLA PRIMARIA,standard
118946,statale,202425,CNEE81103D,SCUOLA PRIMARIA,2,1,0,1,1,0,1.000000,True,L. CUGNOD - PAMPARATO SERRA,CNIC811009,PAMPARATO,CUNEO,DI MONTAGNA,SCUOLA PRIMARIA,standard
6853,statale,202425,PNEE81307E,SCUOLA PRIMARIA,2,5,3,2,0,2,0.400000,True,"MEDUNO ""A.MANZONI""",PNIC813006,MEDUNO,PORDENONE,NORMALE,SCUOLA PRIMARIA,standard
30766,statale,202425,RCEE87302N,SCUOLA PRIMARIA,2,3,2,1,0,1,0.333333,True,PASCOLI,RCIC87300E,REGGIO DI CALABRIA,REGGIO CALABRIA,NORMALE,SCUOLA PRIMARIA,standard
30502,statale,202425,CSEE802054,SCUOLA PRIMARIA,3,3,1,2,2,0,0.666667,True,EE_CAROLEI - VADUE,CSIC80200T,CAROLEI,COSENZA,NORMALE,SCUOLA PRIMARIA,standard

## 5. Unità "irrisolvibili": zero alunni italiani

In [93]:
cla[cla['ANNOCORSOCLASSE']=='7']

         gestione ANNOSCOLASTICO CODICESCUOLA     ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
135       statale         202425   VIEE843024  SCUOLA PRIMARIA               7       1            13              7             20
163       statale         202425   BIEE81907V  SCUOLA PRIMARIA               7       1             6              6             12
280       statale         202425   SAEE8AY06X  SCUOLA PRIMARIA               7       1             8              6             14
456       statale         202425   FREE844044  SCUOLA PRIMARIA               7       1             9              5             14
631       statale         202425   VVEE83503Q  SCUOLA PRIMARIA               7       2            11             16             27
...           ...            ...          ...              ...             ...     ...           ...            ...            ...
127401  paritaria         202425   SA1E00200B  SCUOLA PRIMARIA               7       1             4              6             10
128366  paritaria         202425   NA1E15300P  SCUOLA PRIMARIA               7       1             9              2             11
128537  paritaria         202425   CE1ELF5000  SCUOLA PRIMARIA               7       1             8             12             20
128668  paritaria         202425   RM1EC3500B  SCUOLA PRIMARIA               7       1             8              2             10
130225  paritaria         202425   MS1E00400V  SCUOLA PRIMARIA               7       1             4              7             11

[1409 rows x 9 columns]

In [85]:
ana['DESCRIZIONECARATTERISTICASCUOLA'].value_counts()

DESCRIZIONECARATTERISTICASCUOLA
NORMALE                 48351
PERCORSO II LIVELLO      1521
SPEC. PER CARCERARI       527
C/O IST. OSPEDALIERO      284
DI MONTAGNA               200
ANNESSO A CONVITTO        147
CPIA                      130
ISOLANO                   114
ANNESSO A ISTITUTO         98
CONVITTO ANNESSO           96
SLOVENO                    91
SCUOLA ANNESSA             46
CONVITTO NAZIONALE         37
ANN. A EDUCANDATO          18
Non Disponibile            16
PER SORDOMUTI               8
EDUCANDATO FEMMINILE        5
SPERIMENTALE PER DM         4
PER CIECHI                  3
SPEC. PER SORDOMUTI         3
SPECIALE PER CIECHI         2
DI CONFINE                  2
ANN. A ISTITUTO ARTE        1
Name: count, dtype: int64

In [86]:
ana[ana['DESCRIZIONECARATTERISTICASCUOLA']=='PERCORSO II LIVELLO']

,gestione,ANNOSCOLASTICO,AREAGEOGRAFICA,REGIONE,PROVINCIA,CODICEISTITUTORIFERIMENTO,DENOMINAZIONEISTITUTORIFERIMENTO,CODICESCUOLA,DENOMINAZIONESCUOLA,INDIRIZZOSCUOLA,CAPSCUOLA,CODICECOMUNESCUOLA,DESCRIZIONECOMUNE,DESCRIZIONECARATTERISTICASCUOLA,DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA,INDICAZIONESEDEDIRETTIVO,INDICAZIONESEDEOMNICOMPRENSIVO,INDIRIZZOEMAILSCUOLA,INDIRIZZOPECSCUOLA,SITOWEBSCUOLA,SEDESCOLASTICA,fonte
26,statale,202425,SUD,CAMPANIA,CASERTA,CEIS006006,VAIRANO PATENORA,CERI006517,CORSO SERALE IPIA VAIRANO,VIA DEGLI ABRUZZI,81059,L540,VAIRANO PATENORA,PERCORSO II LIVELLO,IST PROF INDUSTRIA E ARTIGIANATO,NO,Non Disponibile,CEIS006006@istruzione.it,Non Disponibile,www.isissmarconi.it,NO,standard
60,statale,202425,SUD,CALABRIA,VIBO VALENTIA,VVIS003008,IST D'ISTRUZIONE SUPERIORE LUIGI EINAUDI,VVTD00350V,IST. TECN. COMM. E GEOM. CORSO SERALE,Non Disponibile,Non Disponibile,I639,SERRA SAN BRUNO,PERCORSO II LIVELLO,IST TEC COMMERCIALE E PER GEOMETRI,NO,Non Disponibile,VVIS003008@istruzione.it,Non Disponibile,www.iisserrasanbruno.info,NO,standard
69,statale,202425,NORD EST,EMILIA ROMAGNA,RAVENNA,RATD03000R,G.GINANNI,RATD030506,G.GINANNI - CORSO SERALE -,VIA CARDUCCI 11,48100,H199,RAVENNA,PERCORSO II LIVELLO,ISTITUTO TECNICO COMMERCIALE,NO,Non Disponibile,RATD03000R@istruzione.it,Non Disponibile,www.itcginanni.it,NO,standard
133,statale,202425,NORD OVEST,LOMBARDIA,PAVIA,PVIS01200G,IIS COSSA - PAVIA,PVRC01251X,IP COSSA - SERALE - PAVIA,VIALE NECCHI,27100,G388,PAVIA,PERCORSO II LIVELLO,IST PROF PER I SERVIZI COMMERCIALI,NO,Non Disponibile,PVIS01200G@istruzione.it,Non Disponibile,WWW.IISCOSSAPAVIA.EDU.IT,NO,standard
140,statale,202425,NORD OVEST,LOMBARDIA,MILANO,MIIS09400A,L. V. BERTARELLI - FERRARIS,MIRC09451P,I.P.-L. V. BERTARELLI-FERRARIS (SERALE),CORSO DI PORTA ROMANA 110,20122,F205,MILANO,PERCORSO II LIVELLO,IST PROF PER I SERVIZI COMMERCIALI E TURISTICI,NO,Non Disponibile,MIIS09400A@istruzione.it,Non Disponibile,www.bertarelliferraris.edu.it,NO,standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62957,statale,202425,NORD EST,TRENTINO-ALTO ADIGE,TRENTO,TNIS00700N,"""LORENZO GUETTI"" - TIONE DI TRENTO",TNTD007519,LORENZO GUETTI TIONE DI TRENTO -SERALE,"VIA DURONE, 53",38079,L174,TIONE DI TRENTO,PERCORSO II LIVELLO,IST TEC COMMERCIALE E PER GEOMETRI,NO,Non Disponibile,segr.guetti@scuole.provincia.tn.it,Non Disponibile,www.guetti.tn.it,NaN,autonome
62967,statale,202425,NORD EST,TRENTINO-ALTO ADIGE,TRENTO,TNTD18000T,"""A. TAMBOSI"" - TRENTO",TNTD180507,"""A. TAMBOSI "" - TRENTO - SERALE","VIA BRIGATA ACQUI, 19",38122,L378,TRENTO,PERCORSO II LIVELLO,ISTITUTO TECNICO COMMERCIALE,NO,Non Disponibile,Non Disponibile,Non Disponibile,https://tambosi.tn.it/,NaN,autonome
63039,statale,202425,NORD EST,TRENTINO-ALTO ADIGE,TRENTO,TNIS00100P,"""LA ROSA BIANCA-WEISSE ROSE"" - CAVALESE",TNTD001509,LA ROSA BIANCA-WEISSE ROSE SERALE,Non Disponibile,38037,H018,PREDAZZO,PERCORSO II LIVELLO,ISTITUTO TECNICO COMMERCIALE,NO,Non Disponibile,segr.iicavalese@scuole.provincia.tn.it,Non Disponibile,www.rosabianca.tn.it,NaN,autonome
63092,statale,202425,NORD EST,TRENTINO-ALTO ADIGE,TRENTO,TNTD020009,"""FELICE E GREGORIO FONTANA"" - ROVERETO",TNTD02050P,FELICE GREGORIO FONTANA ROVERETO SERALE,"VIA DEL TEATRO, 4",38068,H612,ROVERETO,PERCORSO II LIVELLO,ISTITUTO TECNICO COMMERCIALE,NO,Non Disponibile,segreteria@fgfontana.eu,Non Disponibile,www.fgfontana.eu,NaN,autonome
63133,statale,202425,NORD EST,TRENTINO-ALTO ADIGE,TRENTO,TNIS00300A,"""MARTINO MARTINI"" MEZZOLOMBARDO",TNRC00350N,"""MARTINO MARTINI""-MEZZOLOMBARDO - SERALE","VIA PERLASCA, 4",38017,F187,MEZZOLOMBARDO,PERCORSO II LIVELLO,IST PROF PER I SERVIZI COMMERCIALI E TURISTICI,NO,Non Disponibile,segr.martini.mezzolombardo@scuole.provincia.tn.it,Non Disponibile,www.martinomartini.eu,NaN,autonome

In [25]:
irris = citx[citx['ALUNNICITTADINANZAITALIANA'].eq(0) & citx['ALUNNI'].gt(0)]
display(irris['ALUNNI'].describe())
display(irris.groupby(['gestione', 'ORDINESCUOLA', 'DESCRIZIONECARATTERISTICASCUOLA']).size())
irris.sort_values('ALUNNI', ascending=False).head(20)

count    226.000000
mean       4.008850
std        7.125535
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       62.000000
Name: ALUNNI, dtype: float64

gestione  ORDINESCUOLA                DESCRIZIONECARATTERISTICASCUOLA
statale   SCUOLA PRIMARIA             DI MONTAGNA                         15
                                      ISOLANO                              3
                                      NORMALE                            124
                                      SLOVENO                              2
          SCUOLA SECONDARIA I GRADO   C/O IST. OSPEDALIERO                 1
                                      ISOLANO                              1
                                      NORMALE                             23
          SCUOLA SECONDARIA II GRADO  PERCORSO II LIVELLO                 10
                                      SPEC. PER CARCERARI                  9
dtype: int64

,gestione,ANNOSCOLASTICO,CODICESCUOLA,ORDINESCUOLA,ANNOCORSO,ALUNNI,ALUNNICITTADINANZAITALIANA,ALUNNICITTADINANZANONITALIANA,ALUNNICITTADINANZANONITALIANAPAESIUE,ALUNNICITTADINANZANONITALIANAPAESINONUE,QUOTA,SOPRA_30,DENOMINAZIONESCUOLA,CODICEISTITUTORIFERIMENTO,DESCRIZIONECOMUNE,PROVINCIA,DESCRIZIONECARATTERISTICASCUOLA,DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA,fonte
53874,statale,202425,SAMM87201A,SCUOLA SECONDARIA I GRADO,1,62,0,62,0,62,1.0,True,"POLLA ""E.DE AMICIS""",SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
54613,statale,202425,SAMM87201A,SCUOLA SECONDARIA I GRADO,2,45,0,45,1,44,1.0,True,"POLLA ""E.DE AMICIS""",SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
126868,paritaria,202425,LT1MZZ500E,SCUOLA SECONDARIA I GRADO,3,43,0,43,0,43,1.0,True,C.P.I.A. Lenola,NaN,LENOLA,LATINA,NaN,SCUOLA SEC. PRIMO GRADO NON STATALE,standard
121881,paritaria,202425,LT1MZZ500E,SCUOLA SECONDARIA I GRADO,1,30,0,30,0,30,1.0,True,C.P.I.A. Lenola,NaN,LENOLA,LATINA,NaN,SCUOLA SEC. PRIMO GRADO NON STATALE,standard
56958,statale,202425,SAMM87202B,SCUOLA SECONDARIA I GRADO,2,24,0,24,0,24,1.0,True,CAGGIANO,SAIC872009,CAGGIANO,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
53251,statale,202425,SAMM87202B,SCUOLA SECONDARIA I GRADO,1,20,0,20,0,20,1.0,True,CAGGIANO,SAIC872009,CAGGIANO,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
52651,statale,202425,SAEE87204E,SCUOLA PRIMARIA,1,20,0,20,1,19,1.0,True,CAGGIANO CAP,SAIC872009,CAGGIANO,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
44834,statale,202425,SAEE87201B,SCUOLA PRIMARIA,3,18,0,18,0,18,1.0,True,POLLA CAP.P.P.,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
55986,statale,202425,SAMM87203C,SCUOLA SECONDARIA I GRADO,2,17,0,17,2,15,1.0,True,AULETTA,SAIC872009,AULETTA,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
40443,statale,202425,SAEE87201B,SCUOLA PRIMARIA,1,17,0,17,1,16,1.0,True,POLLA CAP.P.P.,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
55202,statale,202425,SAMM87203C,SCUOLA SECONDARIA I GRADO,1,16,0,16,1,15,1.0,True,AULETTA,SAIC872009,AULETTA,SALERNO,NORMALE,SCUOLA PRIMO GRADO,standard
128653,paritaria,202425,RM1E077009,SCUOLA PRIMARIA,5,16,0,16,0,16,1.0,True,SCUOLA ELEM.PARIF. SACRO CUORE,NaN,ROMA,ROMA,NaN,SCUOLA PRIMARIA NON STATALE,standard
63139,statale,202425,PGEE85902D,SCUOLA PRIMARIA,3,16,0,16,1,15,1.0,True,"""E.PESTALOZZI""",PGIC85900A,PERUGIA,PERUGIA,NORMALE,SCUOLA PRIMARIA,standard
21872,statale,202425,SAEE87202C,SCUOLA PRIMARIA,4,16,0,16,0,16,1.0,True,S. PIETRO,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
23630,statale,202425,SAEE87202C,SCUOLA PRIMARIA,2,16,0,16,0,16,1.0,True,S. PIETRO,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
41165,statale,202425,SAEE87201B,SCUOLA PRIMARIA,2,14,0,14,0,14,1.0,True,POLLA CAP.P.P.,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
59179,statale,202425,SAEE87206L,SCUOLA PRIMARIA,1,14,0,14,0,14,1.0,True,AULETTA CAP.,SAIC872009,AULETTA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
119951,paritaria,202425,NA1E1M500R,SCUOLA PRIMARIA,5,13,0,13,0,13,1.0,True,SCUOLA PRIMARIA ORIENTALE,NaN,NAPOLI,NAPOLI,NaN,SCUOLA PRIMARIA NON STATALE,standard
24392,statale,202425,SAEE87202C,SCUOLA PRIMARIA,3,13,0,13,0,13,1.0,True,S. PIETRO,SAIC872009,POLLA,SALERNO,NORMALE,SCUOLA PRIMARIA,standard
125783,paritaria,202425,NA1E1M500R,SCUOLA PRIMARIA,1,13,0,13,0,13,1.0,True,SCUOLA PRIMARIA ORIENTALE,NaN,NAPOLI,NAPOLI,NaN,SCUOLA PRIMARIA NON STATALE,standard

## 6. Pluriclassi (anno di corso 7) e differenze tra i due flussi

Nel flusso classi, gli alunni delle pluriclassi stanno sotto `ANNOCORSOCLASSE = 7`; nel flusso cittadinanza sono distribuiti sui loro anni di corso effettivi.

In [26]:
cla[cla['ANNOCORSOCLASSE'].eq('7')].groupby(['gestione', 'ORDINESCUOLA']).agg(
    righe=('CLASSI', 'size'), classi=('CLASSI', 'sum'), alunni=('ALUNNI_CLASSI', 'sum'))

                           righe  classi  alunni
gestione  ORDINESCUOLA
paritaria SCUOLA PRIMARIA     17      18     247
statale   SCUOLA PRIMARIA   1392    2080   27355

In [27]:
# Confronto tra i due flussi per plesso: il totale deve tornare includendo l'anno 7
tot_cit = cit.groupby(['gestione', 'CODICESCUOLA', 'ORDINESCUOLA'])['ALUNNI'].sum()
tot_cla = cla.groupby(['gestione', 'CODICESCUOLA', 'ORDINESCUOLA'])['ALUNNI_CLASSI'].sum()
confronto = pd.concat([tot_cit, tot_cla], axis=1).fillna(0)
confronto['delta'] = confronto['ALUNNI'] - confronto['ALUNNI_CLASSI']
print('plessi con totale diverso:', (confronto['delta'] != 0).sum())
confronto[confronto['delta'] != 0]

plessi con totale diverso: 0

Empty DataFrame
Columns: [ALUNNI, ALUNNI_CLASSI, delta]
Index: []

In [28]:
# Caso più vistoso di delta per anno di corso: 58 alunni nel flusso cittadinanza contro 20 nel flusso classi (anno 4)
mostra('PTEE81901N')

--- ANAGRAFE

                                                                        3587
gestione                                                             statale
ANNOSCOLASTICO                                                        202425
AREAGEOGRAFICA                                                        CENTRO
REGIONE                                                              TOSCANA
PROVINCIA                                                            PISTOIA
CODICEISTITUTORIFERIMENTO                                         PTIC81900G
DENOMINAZIONEISTITUTORIFERIMENTO               "C. SALUTATI - A. CAVALCANTI"
CODICESCUOLA                                                      PTEE81901N
DENOMINAZIONESCUOLA                                          "A. CAVALCANTI"
INDIRIZZOSCUOLA                                           PIAZZA ALDO MORO 1
CAPSCUOLA                                                              51011
CODICECOMUNESCUOLA                                                      B251
DESCRIZIONECOMUNE                                                   BUGGIANO
DESCRIZIONECARATTERISTICASCUOLA                                      NORMALE
DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA                    SCUOLA PRIMARIA
INDICAZIONESEDEDIRETTIVO                                                  NO
INDICAZIONESEDEOMNICOMPRENSIVO                               Non Disponibile
INDIRIZZOEMAILSCUOLA                                PTIC81900G@istruzione.it
INDIRIZZOPECSCUOLA                                           Non Disponibile
SITOWEBSCUOLA                              www.istitutosalutaticavalcanti.it
SEDESCOLASTICA                                                            SI
fonte                                                               standard

--- CITTADINANZA

       gestione ANNOSCOLASTICO CODICESCUOLA     ORDINESCUOLA ANNOCORSO  ALUNNI  ALUNNICITTADINANZAITALIANA  ALUNNICITTADINANZANONITALIANA  ALUNNICITTADINANZANONITALIANAPAESIUE  ALUNNICITTADINANZANONITALIANAPAESINONUE     QUOTA  SOPRA_30
103532  statale         202425   PTEE81901N  SCUOLA PRIMARIA         1      61                          46                             15                                     3                                       12  0.245902     False
101275  statale         202425   PTEE81901N  SCUOLA PRIMARIA         2      58                          47                             11                                     3                                        8  0.189655     False
102147  statale         202425   PTEE81901N  SCUOLA PRIMARIA         3      50                          40                             10                                     3                                        7  0.200000     False
106009  statale         202425   PTEE81901N  SCUOLA PRIMARIA         4      58                          48                             10                                     1                                        9  0.172414     False
106739  statale         202425   PTEE81901N  SCUOLA PRIMARIA         5      60                          43                             17                                     3                                       14  0.283333     False

--- CLASSI/STUDENTI

      gestione ANNOSCOLASTICO CODICESCUOLA     ORDINESCUOLA ANNOCORSOCLASSE  CLASSI  ALUNNIMASCHI  ALUNNIFEMMINE  ALUNNI_CLASSI
15589  statale         202425   PTEE81901N  SCUOLA PRIMARIA               1       3            33             28             61
98581  statale         202425   PTEE81901N  SCUOLA PRIMARIA               2       3            25             33             58
26773  statale         202425   PTEE81901N  SCUOLA PRIMARIA               3       3            25             25             50
29392  statale         202425   PTEE81901N  SCUOLA PRIMARIA               4       1            11              9             20
61695  statale         202425   PTEE81901N  SCUOLA PRIMARIA               5       3            25             35             60
65356  statale         202425   PTEE81901N  SCUOLA PRIMARIA               7       2            17             21             38

In [29]:
# Tutte le unità con delta != 0 sull'anno di corso esatto
uc[uc['CLASSI'].notna() & uc['ALUNNI'].ne(uc['ALUNNI_CLASSI'])].sort_values('CODICESCUOLA')

,gestione,ANNOSCOLASTICO,CODICESCUOLA,ORDINESCUOLA,ANNOCORSO,ALUNNI,ALUNNICITTADINANZAITALIANA,ALUNNICITTADINANZANONITALIANA,ALUNNICITTADINANZANONITALIANAPAESIUE,ALUNNICITTADINANZANONITALIANAPAESINONUE,QUOTA,SOPRA_30,CLASSI,ALUNNI_CLASSI,ALUNNI_PER_CLASSE
25309,statale,202425,APEE81301X,SCUOLA PRIMARIA,1,27,22,5,1,4,0.185185,False,1.0,18.0,27.0
26069,statale,202425,APEE81301X,SCUOLA PRIMARIA,2,24,19,5,1,4,0.208333,False,1.0,20.0,24.0
63699,statale,202425,BTEE86402E,SCUOLA PRIMARIA,3,4,4,0,0,0,0.000000,False,1.0,2.0,4.0
64484,statale,202425,BTEE86402E,SCUOLA PRIMARIA,4,7,7,0,0,0,0.000000,False,1.0,5.0,7.0
92017,statale,202425,IMEE81102P,SCUOLA PRIMARIA,3,30,13,17,3,14,0.566667,True,1.0,24.0,30.0
87445,statale,202425,IMEE81102P,SCUOLA PRIMARIA,5,33,22,11,0,11,0.333333,True,1.0,23.0,33.0
77395,statale,202425,MIEE8C504G,SCUOLA PRIMARIA,5,10,6,4,0,4,0.400000,True,2.0,5.0,5.0
111926,statale,202425,MTEE81803Q,SCUOLA PRIMARIA,5,23,22,1,0,1,0.043478,False,1.0,12.0,23.0
72109,statale,202425,PDEE854058,SCUOLA PRIMARIA,3,32,24,8,0,8,0.250000,False,1.0,22.0,32.0
75846,statale,202425,PDEE854058,SCUOLA PRIMARIA,4,29,23,6,2,4,0.206897,False,1.0,20.0,29.0
15551,statale,202425,PGEE04112R,SCUOLA PRIMARIA,1,4,3,1,1,0,0.250000,False,1.0,1.0,4.0
106009,statale,202425,PTEE81901N,SCUOLA PRIMARIA,4,58,48,10,1,9,0.172414,False,1.0,20.0,58.0
17658,statale,202425,RIEE82504V,SCUOLA PRIMARIA,3,19,11,8,3,5,0.421053,True,1.0,16.0,19.0
88513,statale,202425,SOEE815038,SCUOLA PRIMARIA,5,23,21,2,0,2,0.086957,False,1.0,16.0,23.0
70371,statale,202425,SPEE82401V,SCUOLA PRIMARIA,1,36,32,4,2,2,0.111111,False,1.0,23.0,36.0
71163,statale,202425,SPEE82401V,SCUOLA PRIMARIA,2,24,21,3,1,2,0.125000,False,1.0,19.0,24.0
19123,statale,202425,TAEE83901R,SCUOLA PRIMARIA,3,84,71,13,2,11,0.154762,False,4.0,77.0,21.0
15306,statale,202425,TAEE83901R,SCUOLA PRIMARIA,4,101,86,15,2,13,0.148515,False,5.0,96.0,20.2
85173,statale,202425,UDEE856049,SCUOLA PRIMARIA,2,11,6,5,0,5,0.454545,True,2.0,3.0,5.5
51758,statale,202425,UDEE856049,SCUOLA PRIMARIA,5,12,8,4,2,2,0.333333,True,2.0,5.0,6.0
51970,statale,202425,VEEE85602V,SCUOLA PRIMARIA,2,29,25,4,0,4,0.137931,False,1.0,15.0,29.0

## 7. Casi minori: anno di corso 6, codici duplicati in anagrafe, righe non unibili

In [30]:
citx[citx['ANNOCORSO'].eq('6')][
    ['gestione', 'CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA',
     'ALUNNI', 'ALUNNICITTADINANZANONITALIANA']]

       gestione CODICESCUOLA                       DENOMINAZIONESCUOLA DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA  ALUNNI  ALUNNICITTADINANZANONITALIANA
7974    statale   CNTA012015                          ALBA "UMBERTO I"                  ISTITUTO TECNICO AGRARIO      18                              0
24280   statale   BTTD04301R  "R. LOTTI-UMBERTO I" TEC.TURISMO-AGRARIO              ISTITUTO TECNICO COMMERCIALE       7                              1
30402   statale   RMTA06000E                             EMILIO SERENI                  ISTITUTO TECNICO AGRARIO       9                              0
31897   statale   AVTA028012                      FRANCESCO DE SANCTIS                  ISTITUTO TECNICO AGRARIO      15                              0
35904   statale   ANTA01701E                        GIUSEPPE VIVARELLI                  ISTITUTO TECNICO AGRARIO       6                              0
37589   statale   APTA00801A                  ISTITUTO TECNICO AGRARIO                  ISTITUTO TECNICO AGRARIO      12                              0
41535   statale   MCTA009019             "GIUSEPPE GARIBALDI" MACERATA                  ISTITUTO TECNICO AGRARIO       9                              0
45338   statale   SITA00901G                IST. TECNICO AGRARIO SIENA                  ISTITUTO TECNICO AGRARIO      10                              1
45514   statale   META00901E                            PIETRO CUPPARI                  ISTITUTO TECNICO AGRARIO      17                              0
47204   statale   PVTA01000P                     ITA GALLINI - VOGHERA                  ISTITUTO TECNICO AGRARIO      17                              0
55967   statale   CTTA00401L                CUCUZZA-EUCLIDE - SEZ. ITA                  ISTITUTO TECNICO AGRARIO      11                              0
63437   statale   UDTA00701V                         ITA P. D'AQUILEIA                  ISTITUTO TECNICO AGRARIO      14                              1
63724   statale   FGTA01101E                      I.T. "G. PAVONCELLI"                  ISTITUTO TECNICO AGRARIO      16                              0
81218   statale   BATA024029                            BASILE CARAMIA                  ISTITUTO TECNICO AGRARIO      13                              0
89931   statale   TPTA01201G    IST. TEC. AGRARIO "A. DAMIANI" MARSALA                  ISTITUTO TECNICO AGRARIO      19                              0
95040   statale   PCTA00201P                                 G.RAINERI                  ISTITUTO TECNICO AGRARIO       7                              0
100441  statale   VTTA01601G       IST. TECNICO AGRARIO "F.LLI AGOSTI"                  ISTITUTO TECNICO AGRARIO      23                              1
102453  statale   AGTA012016   IST. TECNICO AGRARIO "C. AMATO VETRANO"                  ISTITUTO TECNICO AGRARIO      11                              0
110779  statale   TVTA00801A                       I.T.A.A.A. CERLETTI                  ISTITUTO TECNICO AGRARIO      32                              0
115182  statale   CATA01401E               I.T.A. "DUCA DEGLI ABRUZZI"                  ISTITUTO TECNICO AGRARIO      16                              0

In [31]:
# Codici presenti più volte nelle anagrafi (analyze.py tiene il primo, cioè l'anagrafe standard)
dup = ana[ana['CODICESCUOLA'].duplicated(keep=False)].sort_values(['CODICESCUOLA', 'fonte'])
print('codici duplicati:', dup['CODICESCUOLA'].nunique())
dup[['gestione', 'fonte', 'CODICESCUOLA', 'DENOMINAZIONESCUOLA', 'CODICEISTITUTORIFERIMENTO', 'DESCRIZIONECOMUNE']].head(20)

codici duplicati: 0

Empty DataFrame
Columns: [gestione, fonte, CODICESCUOLA, DENOMINAZIONESCUOLA, CODICEISTITUTORIFERIMENTO, DESCRIZIONECOMUNE]
Index: []

In [32]:
# Righe del flusso classi senza corrispondente nel flusso cittadinanza (escluso l'anno 7)
chiave_cla = ['gestione', 'CODICESCUOLA', 'ORDINESCUOLA', 'ANNOCORSOCLASSE']
orfane = cla[cla['ANNOCORSOCLASSE'].ne('7')].merge(
    cit.rename(columns={'ANNOCORSO': 'ANNOCORSOCLASSE'})[chiave_cla],
    on=chiave_cla, how='left', indicator=True,
)
orfane[orfane['_merge'].eq('left_only')]

Empty DataFrame
Columns: [gestione, ANNOSCOLASTICO, CODICESCUOLA, ORDINESCUOLA, ANNOCORSOCLASSE, CLASSI, ALUNNIMASCHI, ALUNNIFEMMINE, ALUNNI_CLASSI, _merge]
Index: []

In [95]:
df_units = pd.read_csv('../data_processed/unita_202425.csv')

In [97]:
df_units[df_units['codice_scuola']=='NON DISPONIBILE']

Empty DataFrame
Columns: [anno_scolastico, tipo_gestione, codice_scuola, denominazione_scuola, codice_istituto_riferimento, denominazione_istituto_riferimento, ordine_scuola, anno_corso, area_geografica, regione, provincia, codice_comune, comune, indirizzo_scuola, cap_scuola, tipo_scuola_anagrafe, fonte_anagrafe, anagrafe_mappata, alunni_italiani, alunni_non_italiani, alunni_totali, quota_non_italiani, sopra_30, m_min, m_min_irrisolvibile, m_min_con_sostituzione_legacy, classi_esatte, alunni_classi_esatte, delta_n_cittadinanza_meno_classi, chiave_classi_confrontabile]
Index: []

In [99]:
df_units['m_min_irrisolvibile'].value_counts(
)

m_min_irrisolvibile
0    134558
1       226
Name: count, dtype: int64

In [100]:
controllo_join = pd.read_csv('../results/controlli_join_202425.csv')

In [101]:
controllo_join

    anno_scolastico tipo_gestione                 dataset              passaggio                                         esito   righe  plessi     alunni                                               nota
0            202425       statale                anagrafe            caricamento                                  codici_unici   51704   51704        NaN  50515 righe standard + 1189 autonome; 0 codici...
1            202425       statale                anagrafe  join con cittadinanza               codice_presente_in_cittadinanza   28040   28040        NaN                                                NaN
2            202425       statale                anagrafe  join con cittadinanza                codice_assente_da_cittadinanza   23664   23664        NaN  Plessi senza alunni di primaria/secondaria: in...
3            202425       statale            cittadinanza            caricamento                                  righe_totali  119793   28040  6172717.0                                                NaN
4            202425       statale            cittadinanza      join con anagrafe                     esclusa_anagrafe_mancante       0       0        0.0                                                NaN
5            202425       statale            cittadinanza      join con anagrafe   esclusa_caratteristica: PERCORSO II LIVELLO    3257    1180    76783.0                                                NaN
6            202425       statale            cittadinanza      join con anagrafe    esclusa_caratteristica: ANNESSO A CONVITTO     586     134    36036.0                                                NaN
7            202425       statale            cittadinanza      join con anagrafe      esclusa_caratteristica: CONVITTO ANNESSO     473      93    29182.0                                                NaN
8            202425       statale            cittadinanza      join con anagrafe        esclusa_caratteristica: SCUOLA ANNESSA     224      45    17337.0                                                NaN
9            202425       statale            cittadinanza      join con anagrafe               esclusa_caratteristica: ISOLANO     385      87    11658.0                                                NaN
10           202425       statale            cittadinanza      join con anagrafe   esclusa_caratteristica: SPEC. PER CARCERARI     519     172     6965.0                                                NaN
11           202425       statale            cittadinanza      join con anagrafe     esclusa_caratteristica: ANN. A EDUCANDATO      78      18     6220.0                                                NaN
12           202425       statale            cittadinanza      join con anagrafe               esclusa_caratteristica: SLOVENO     202      44     3154.0                                                NaN
13           202425       statale            cittadinanza      join con anagrafe           esclusa_caratteristica: DI MONTAGNA     354      79     2632.0                                                NaN
14           202425       statale            cittadinanza      join con anagrafe   esclusa_caratteristica: SPERIMENTALE PER DM      12       4      680.0                                                NaN
15           202425       statale            cittadinanza      join con anagrafe         esclusa_caratteristica: PER SORDOMUTI      18       4      669.0                                                NaN
16           202425       statale            cittadinanza      join con anagrafe            esclusa_caratteristica: PER CIECHI       9       3      376.0                                                NaN
17           202425       statale            cittadinanza      join con anagrafe   esclusa_caratteristica: SPEC. PER SORDOMUTI       5       1       80.0                                                NaN
18           202425       statale            cittadinanza      join con anagrafe   esclusa_caratteristica: SPECIALE PER CIECHI       1       1       26.0                                                NaN
19           202425       statale            cittadinanza      join con anagrafe  esclusa_caratteristica: ANN. A ISTITUTO ARTE       3       1       18.0                                                NaN
20           202425       statale            cittadinanza      join con anagrafe  esclusa_caratteristica: C/O IST. OSPEDALIERO       2       2        3.0                                                NaN
21           202425       statale            cittadinanza      join con anagrafe                          inclusa_nell_analisi  113665   26172  5980898.0                       Solo caratteristica NORMALE.
22           202425       statale  cittadinanza (incluse)        join con classi                          chiave_classi_esatta  109020   25652  5954672.0                                                NaN
23           202425       statale  cittadinanza (incluse)        join con classi    senza_chiave_classi_plesso_con_pluriclassi    4645    1329    26226.0  Alunni in pluriclasse: nel flusso classi sono ...
24           202425       statale  cittadinanza (incluse)        join con classi                     senza_chiave_classi_altro       0       0        0.0                                                NaN
25           202425       statale                  classi            caricamento                                  righe_totali  116317   28040  6172717.0                                                NaN
26           202425       statale                  classi  join con cittadinanza                         unita_a_unita_incluse  109020   25652  5954494.0                                                NaN
27           202425       statale                  classi  join con cittadinanza             plesso_incluso_anno_7_pluriclasse    1335    1335    26404.0  Non unibili per costruzione: la pluriclasse me...
28           202425       statale                  classi  join con cittadinanza             plesso_incluso_chiave_senza_unita       0       0        0.0                                                NaN
29           202425       statale                  classi  join con cittadinanza                   plesso_escluso_dall_analisi    5962    1868   191819.0  Plessi scartati nel join cittadinanza-anagrafe...
30           202425       statale                  classi  join con cittadinanza                plesso_assente_da_cittadinanza       0       0        0.0                                                NaN
31           202425     paritaria                anagrafe            caricamento                                  codici_unici   11565   11565        NaN  11497 righe standard + 68 autonome; 0 codici d...
32           202425     paritaria                anagrafe  join con cittadinanza               codice_presente_in_cittadinanza    3473    3473        NaN                                                NaN
33           202425     paritaria                anagrafe  join con cittadinanza                codice_assente_da_cittadinanza    8092    8092        NaN  Plessi senza alunni di primaria/secondaria: in...
34           202425     paritaria            cittadinanza            caricamento                                  righe_totali   14991    3473   342921.0                                                NaN
35           202425     paritaria            cittadinanza      join con anagrafe                     esclusa_anagrafe_mancante       0       0        0.0                                                NaN
36           202425     paritaria            cittadinanza      join con anagrafe                          inclusa_nell_analisi   14991    3473   342921.0  Filtro sulla caratteristica non applicabile: c...
37           202425     paritaria  cittadinanza (incluse)        join con classi                          chiave_classi_esatta   14949    3469   342674.0                                                NaN
38           202425     paritaria  cittadinanza (incluse)        join con classi    senza_chiave_classi_plesso_con_pluriclassi      42      17      247.0  Alunni in pluriclasse: nel flusso classi sono ...
39           202425     paritaria  cittadinanza (incluse)        join con classi                     senza_chiave_classi_altro       0       0        0.0                                                NaN
40           202425     paritaria                  classi            caricamento                                  righe_totali   14966    3473   342921.0                                                NaN
41           202425     paritaria                  classi  join con cittadinanza                         unita_a_unita_incluse   14949    3469   342674.0                                                NaN
42           202425     paritaria                  classi  join con cittadinanza             plesso_incluso_anno_7_pluriclasse      17      17      247.0  Non unibili per costruzione: la pluriclasse me...
43           202425     paritaria                  classi  join con cittadinanza             plesso_incluso_chiave_senza_unita       0       0        0.0                                                NaN
44           202425     paritaria                  classi  join con cittadinanza                   plesso_escluso_dall_analisi       0       0        0.0  Plessi scartati nel join cittadinanza-anagrafe...
45           202425     paritaria                  classi  join con cittadinanza                plesso_assente_da_cittadinanza       0       0        0.0                                                NaN

In [104]:
cit['ANNOCORSO'].value_counts()

ANNOCORSO
3    30047
2    29616
1    29499
5    22863
4    22739
6       20
Name: count, dtype: int64

In [105]:
cla['ANNOCORSOCLASSE'].value_counts()

ANNOCORSOCLASSE
3    29042
2    28564
1    28549
5    21969
4    21730
7     1409
6       20
Name: count, dtype: int64

In [107]:
cit['ALUNNICITTADINANZANONITALIANA'].sum()

762050

In [1]:
import pandas as pd

In [98]:
df = pd.read_csv('../data_processed/unita_202425.csv')

In [99]:
df[df['sopra_30']==1]['anno_corso'].value_counts()

anno_corso
1    3287
2    2971
3    2613
4    1996
5    1925
Name: count, dtype: int64

In [20]:
import numpy as np
import pandas as pd
df_geocoded = pd.read_csv('../data_processed/geocoding_scuole_202425.csv')
df_unita = pd.read_csv('../data_processed/unita_202425.csv')

def haversine_km(lat1: float, lon1: float, lat2_arr: np.ndarray, lon2_arr: np.ndarray) -> np.ndarray:
    """Distanza geodetica (km) da un punto a un array di punti (radianti)."""

    dlat = lat2_arr - lat1
    dlon = lon2_arr - lon1
    a = np.sin(dlat / 2.0) ** 2 + math.cos(lat1) * np.cos(lat2_arr) * np.sin(dlon / 2.0) ** 2
    c = 2.0 * np.arcsin(np.minimum(1.0, np.sqrt(a)))
    return EARTH_RADIUS_KM * c

In [32]:
df_unita[df_unita['classi_esatte'].isna()]=1

In [33]:
df_unita['capienza'] = df_unita['classi_esatte']*26

In [34]:
#escludiamo classi solo stranieri
df_unita = df_unita[df_unita['m_min_irrisolvibile']==0]

In [35]:
df_unita['rimanenza'] = df_unita['capienza'] - df_unita['alunni_totali']
df_unita.loc[df_unita['rimanenza']<0, 'rimanenza'] = 0

#numero teorico di stranieri in una scuole per non superare il 30%
df_unita['disponibilita_stranieri'] = round((0.3*df_unita['alunni_totali'] - df_unita['alunni_non_italiani']) / 0.7)  

#numero effettivo (capienza - numero teorico di stranieri, cappato inferiormente a 0)
df_unita['disponibilita_effettiva'] = df_unita['rimanenza']-df_unita['disponibilita_stranieri']
df_unita.loc[df_unita['disponibilita_effettiva']<=0, 'disponibilita_effettiva'] = 0

In [36]:
df_unita = df_unita[df_unita['anno_corso']==1]

In [37]:
comuni={}
for comune in df_unita['comune'].unique():
    voci_comune = []
    df_comune = df_unita[df_unita['comune']==comune]
    for ordine_scuola in df_comune['ordine_scuola'].unique():
        df_ordine = df_comune[df_comune['ordine_scuola']==ordine_scuola]

        for tipo_scuola_anagrafe in df_ordine['tipo_scuola_anagrafe'].unique():
            df_tipo_scuola = df_ordine[df_ordine['tipo_scuola_anagrafe']==tipo_scuola_anagrafe]

            tot_disponibilita_effettiva = df_tipo_scuola['disponibilita_effettiva'].sum()
            tot_da_rilocare = df_tipo_scuola['m_min'].sum()
            differenza = tot_da_rilocare-tot_disponibilita_effettiva

            if differenza>0: 
                comune_dict = {'comune':comune, 'tipo_scuola':tipo_scuola_anagrafe, 'ordine_scuola':ordine_scuola,'studenti_senza_posto':differenza, 'studenti_da_spostare': tot_da_rilocare, 'disponibilita_effettiva':tot_disponibilita_effettiva}
                voci_comune.append(comune_dict)
        
    if voci_comune:
        comuni[comune]=voci_comune

In [38]:
comuni

{'PARMA': [{'comune': 'PARMA',
   'tipo_scuola': 'IST PROF INDUSTRIA E ARTIGIANATO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 37.0,
   'disponibilita_effettiva': 36.0}],
 'PIACENZA': [{'comune': 'PIACENZA',
   'tipo_scuola': 'IST PROF PER I SERVIZI COMMERCIALI E TURISTICI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 25.0,
   'disponibilita_effettiva': 24.0},
  {'comune': 'PIACENZA',
   'tipo_scuola': 'IST PROF INDUSTRIA E ARTIGIANATO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 22.0,
   'disponibilita_effettiva': 21.0}],
 'GENOVA': [{'comune': 'GENOVA',
   'tipo_scuola': 'IST PROF INDUSTRIA E ARTIGIANATO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 2.0,
   'studenti_da_spostare': 40.0,
   'disponibilita_effettiva': 38.0},
  {'comune': 'GENOVA',
   'tipo_scuola': 'ISTITUTO TECNICO PER IL TURISMO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 1.0,
   'disponibilita_effettiva': 0.0}],
 'IMPERIA': [{'comune': 'IMPERIA',
   'tipo_scuola': 'IST PROF PER I SERVIZI COMMERCIALI E TURISTICI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'CALCINATE': [{'comune': 'CALCINATE',
   'tipo_scuola': 'SCUOLA PRIMO GRADO',
   'ordine_scuola': 'SCUOLA SECONDARIA I GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'NERETO': [{'comune': 'NERETO',
   'tipo_scuola': 'ISTITUTO TECNICO COMMERCIALE',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 13.0,
   'disponibilita_effettiva': 12.0}],
 'SAN GENNARO VESUVIANO': [{'comune': 'SAN GENNARO VESUVIANO',
   'tipo_scuola': "IST PROF PER L'AGRICOLTURA E L'AMBIENTE",
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 3.0,
   'disponibilita_effettiva': 2.0}],
 'MOLINELLA': [{'comune': 'MOLINELLA',
   'tipo_scuola': 'IST PROF PER I SERVIZI COMMERCIALI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 2.0,
   'disponibilita_effettiva': 1.0}],
 'BONDENO': [{'comune': 'BONDENO',
   'tipo_scuola': 'IST PROF PER I SERVIZI COMMERCIALI E TURISTICI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'PORTOMAGGIORE': [{'comune': 'PORTOMAGGIORE',
   'tipo_scuola': 'ISTITUTO TECNICO COMMERCIALE',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 27.0,
   'disponibilita_effettiva': 26.0}],
 'ROCCABIANCA': [{'comune': 'ROCCABIANCA',
   'tipo_scuola': 'SCUOLA PRIMO GRADO',
   'ordine_scuola': 'SCUOLA SECONDARIA I GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 2.0,
   'disponibilita_effettiva': 1.0}],
 'VALVASONE ARZENE': [{'comune': 'VALVASONE ARZENE',
   'tipo_scuola': 'SCUOLA PRIMO GRADO',
   'ordine_scuola': 'SCUOLA SECONDARIA I GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'ORTE': [{'comune': 'ORTE',
   'tipo_scuola': 'IST TEC COMMERCIALE E PER GEOMETRI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 2.0,
   'disponibilita_effettiva': 1.0}],
 'SARNICO': [{'comune': 'SARNICO',
   'tipo_scuola': 'ISTITUTO TECNICO INDUSTRIALE',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'SAN ZENO NAVIGLIO': [{'comune': 'SAN ZENO NAVIGLIO',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 1.0,
   'disponibilita_effettiva': 0.0}],
 'GUSSOLA': [{'comune': 'GUSSOLA',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 1.0,
   'disponibilita_effettiva': 0.0}],
 'ROMANENGO': [{'comune': 'ROMANENGO',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'PONTECURONE': [{'comune': 'PONTECURONE',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 8.0,
   'disponibilita_effettiva': 7.0},
  {'comune': 'PONTECURONE',
   'tipo_scuola': 'SCUOLA PRIMO GRADO',
   'ordine_scuola': 'SCUOLA SECONDARIA I GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'ROSIGNANO MARITTIMO': [{'comune': 'ROSIGNANO MARITTIMO',
   'tipo_scuola': 'IST PROF INDUSTRIA E ARTIGIANATO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'PESCIA': [{'comune': 'PESCIA',
   'tipo_scuola': 'IST PROF INDUSTRIA E ARTIGIANATO',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 12.0,
   'disponibilita_effettiva': 11.0}],
 'MARSCIANO': [{'comune': 'MARSCIANO',
   'tipo_scuola': 'IST PROF PER I SERVIZI COMMERCIALI',
   'ordine_scuola': 'SCUOLA SECONDARIA II GRADO',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 5.0,
   'disponibilita_effettiva': 4.0}],
 'STANGHELLA': [{'comune': 'STANGHELLA',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 4.0,
   'disponibilita_effettiva': 3.0}],
 'GAMBELLARA': [{'comune': 'GAMBELLARA',
   'tipo_scuola': 'SCUOLA PRIMARIA',
   'ordine_scuola': 'SCUOLA PRIMARIA',
   'studenti_senza_posto': 1.0,
   'studenti_da_spostare': 7.0,
   'disponibilita_effettiva': 6.0}]}

# Analisi quante classi > 30%

In [4]:
df_unita = df_unita[df_unita['alunni_totali']>9]

In [6]:
pd.set_option('display.max_columns', None)

In [8]:
df_unita['m_min_irrisolvibile'].value_counts()

m_min_irrisolvibile
0    115428
1        26
Name: count, dtype: int64

In [12]:
((df_unita['m_min_irrisolvibile']==0) & (df_unita['sopra_30']==1)).value_counts(normalize=True)

False    0.904092
True     0.095908
Name: proportion, dtype: float64

In [19]:
df_unita[(df_unita['m_min_irrisolvibile']==0) & (df_unita['sopra_30']==1)]['provincia'].value_counts().iloc[:30]

provincia
MILANO                   1107
ROMA                      622
BRESCIA                   515
TORINO                    495
BERGAMO                   466
BOLOGNA                   361
VERONA                    311
MODENA                    266
PADOVA                    261
TREVISO                   256
MANTOVA                   239
PAVIA                     239
FIRENZE                   238
GENOVA                    234
CREMONA                   208
VENEZIA                   208
PARMA                     206
REGGIO EMILIA             179
PERUGIA                   176
VICENZA                   170
VARESE                    169
PRATO                     168
ALESSANDRIA               157
PIACENZA                  154
FERRARA                   144
MONZA E DELLA BRIANZA     134
NAPOLI                    131
CUNEO                     131
UDINE                     129
LODI                      128
Name: count, dtype: int64

In [10]:
df_unita[df_unita['m_min_irrisolvibile']==1]

,anno_scolastico,tipo_gestione,codice_scuola,denominazione_scuola,codice_istituto_riferimento,denominazione_istituto_riferimento,ordine_scuola,anno_corso,area_geografica,regione,provincia,codice_comune,comune,indirizzo_scuola,cap_scuola,tipo_scuola_anagrafe,caratteristica_scuola,fonte_anagrafe,anagrafe_mappata,alunni_italiani,alunni_non_italiani,alunni_totali,quota_non_italiani,sopra_30,m_min,m_min_irrisolvibile,m_min_con_sostituzione_legacy,classi_esatte,alunni_classi_esatte,delta_n_cittadinanza_meno_classi,chiave_classi_confrontabile
2163,202425,paritaria,NA1E1M500R,SCUOLA PRIMARIA ORIENTALE,NaN,NaN,SCUOLA PRIMARIA,1,SUD,CAMPANIA,NAPOLI,F839,NAPOLI,VIA E. GIANTURCO 54/B,80146,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,13,13,1.0,1,NaN,1,10,1.0,13.0,0.0,1
2164,202425,paritaria,NA1E1M500R,SCUOLA PRIMARIA ORIENTALE,NaN,NaN,SCUOLA PRIMARIA,2,SUD,CAMPANIA,NAPOLI,F839,NAPOLI,VIA E. GIANTURCO 54/B,80146,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,12,12,1.0,1,NaN,1,9,1.0,12.0,0.0,1
2166,202425,paritaria,NA1E1M500R,SCUOLA PRIMARIA ORIENTALE,NaN,NaN,SCUOLA PRIMARIA,4,SUD,CAMPANIA,NAPOLI,F839,NAPOLI,VIA E. GIANTURCO 54/B,80146,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,11,11,1.0,1,NaN,1,8,1.0,11.0,0.0,1
2167,202425,paritaria,NA1E1M500R,SCUOLA PRIMARIA ORIENTALE,NaN,NaN,SCUOLA PRIMARIA,5,SUD,CAMPANIA,NAPOLI,F839,NAPOLI,VIA E. GIANTURCO 54/B,80146,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,13,13,1.0,1,NaN,1,10,1.0,13.0,0.0,1
4866,202425,paritaria,LT1MZZ500E,C.P.I.A. Lenola,NaN,NaN,SCUOLA SECONDARIA I GRADO,1,CENTRO,LAZIO,LATINA,E527,LENOLA,VIA SANTA CROCE 16,04025,SCUOLA SEC. PRIMO GRADO NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,30,30,1.0,1,NaN,1,21,1.0,30.0,0.0,1
4868,202425,paritaria,LT1MZZ500E,C.P.I.A. Lenola,NaN,NaN,SCUOLA SECONDARIA I GRADO,3,CENTRO,LAZIO,LATINA,E527,LENOLA,VIA SANTA CROCE 16,04025,SCUOLA SEC. PRIMO GRADO NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,43,43,1.0,1,NaN,1,31,2.0,43.0,0.0,1
5450,202425,paritaria,RM1E077009,SCUOLA ELEM.PARIF. SACRO CUORE,NaN,NaN,SCUOLA PRIMARIA,4,CENTRO,LAZIO,ROMA,H501,ROMA,VIA ISABELLA DE ROSIS 8,00177,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,12,12,1.0,1,NaN,1,9,1.0,12.0,0.0,1
5451,202425,paritaria,RM1E077009,SCUOLA ELEM.PARIF. SACRO CUORE,NaN,NaN,SCUOLA PRIMARIA,5,CENTRO,LAZIO,ROMA,H501,ROMA,VIA ISABELLA DE ROSIS 8,00177,SCUOLA PRIMARIA NON STATALE,NON DISPONIBILE (PARITARIA),standard,1,0,16,16,1.0,1,NaN,1,12,1.0,16.0,0.0,1
34571,202425,statale,SAEE87206L,AULETTA CAP.,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,1,SUD,CAMPANIA,SALERNO,A495,AULETTA,VIA LARGO CAPPELLI,84031,SCUOLA PRIMARIA,NORMALE,standard,1,0,14,14,1.0,1,NaN,1,10,1.0,14.0,0.0,1
34576,202425,statale,SAMM87203C,AULETTA,SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,1,SUD,CAMPANIA,SALERNO,A495,AULETTA,VIA LARGO CAPPELLI,84031,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,16,16,1.0,1,NaN,1,12,1.0,16.0,0.0,1
34577,202425,statale,SAMM87203C,AULETTA,SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,2,SUD,CAMPANIA,SALERNO,A495,AULETTA,VIA LARGO CAPPELLI,84031,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,17,17,1.0,1,NaN,1,12,1.0,17.0,0.0,1
34774,202425,statale,SAEE87204E,CAGGIANO CAP,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,1,SUD,CAMPANIA,SALERNO,B351,CAGGIANO,VIA CAFARO FORTUNATO 1,84030,SCUOLA PRIMARIA,NORMALE,standard,1,0,20,20,1.0,1,NaN,1,14,1.0,20.0,0.0,1
34775,202425,statale,SAEE87204E,CAGGIANO CAP,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,2,SUD,CAMPANIA,SALERNO,B351,CAGGIANO,VIA CAFARO FORTUNATO 1,84030,SCUOLA PRIMARIA,NORMALE,standard,1,0,10,10,1.0,1,NaN,1,7,1.0,10.0,0.0,1
34776,202425,statale,SAEE87204E,CAGGIANO CAP,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,3,SUD,CAMPANIA,SALERNO,B351,CAGGIANO,VIA CAFARO FORTUNATO 1,84030,SCUOLA PRIMARIA,NORMALE,standard,1,0,10,10,1.0,1,NaN,1,7,1.0,10.0,0.0,1
34779,202425,statale,SAMM87202B,CAGGIANO,SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,1,SUD,CAMPANIA,SALERNO,B351,CAGGIANO,VIA CAFARO FORTUNATO 3,84030,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,20,20,1.0,1,NaN,1,14,1.0,20.0,0.0,1
34780,202425,statale,SAMM87202B,CAGGIANO,SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,2,SUD,CAMPANIA,SALERNO,B351,CAGGIANO,VIA CAFARO FORTUNATO 3,84030,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,24,24,1.0,1,NaN,1,17,1.0,24.0,0.0,1
36082,202425,statale,SAEE87201B,POLLA CAP.P.P.,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,1,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA A. ISOLDI N.1,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,17,17,1.0,1,NaN,1,12,1.0,17.0,0.0,1
36083,202425,statale,SAEE87201B,POLLA CAP.P.P.,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,2,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA A. ISOLDI N.1,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,14,14,1.0,1,NaN,1,10,1.0,14.0,0.0,1
36084,202425,statale,SAEE87201B,POLLA CAP.P.P.,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,3,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA A. ISOLDI N.1,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,18,18,1.0,1,NaN,1,13,1.0,18.0,0.0,1
36085,202425,statale,SAEE87201B,POLLA CAP.P.P.,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,4,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA A. ISOLDI N.1,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,11,11,1.0,1,NaN,1,8,1.0,11.0,0.0,1
36088,202425,statale,SAEE87202C,S. PIETRO,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,2,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA GARIBALDI,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,16,16,1.0,1,NaN,1,12,1.0,16.0,0.0,1
36089,202425,statale,SAEE87202C,S. PIETRO,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,3,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA GARIBALDI,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,13,13,1.0,1,NaN,1,10,1.0,13.0,0.0,1
36090,202425,statale,SAEE87202C,S. PIETRO,SAIC872009,I.O.C. POLLA,SCUOLA PRIMARIA,4,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA GARIBALDI,84035,SCUOLA PRIMARIA,NORMALE,standard,1,0,16,16,1.0,1,NaN,1,12,1.0,16.0,0.0,1
36092,202425,statale,SAMM87201A,"POLLA ""E.DE AMICIS""",SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,1,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA ANNIA N. 1,84035,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,62,62,1.0,1,NaN,1,44,3.0,62.0,0.0,1
36093,202425,statale,SAMM87201A,"POLLA ""E.DE AMICIS""",SAIC872009,I.O.C. POLLA,SCUOLA SECONDARIA I GRADO,2,SUD,CAMPANIA,SALERNO,G793,POLLA,VIA ANNIA N. 1,84035,SCUOLA PRIMO GRADO,NORMALE,standard,1,0,45,45,1.0,1,NaN,1,32,2.0,45.0,0.0,1
117927,202425,statale,PGEE85902D,"""E.PESTALOZZI""",PGIC85900A,I.C. PERUGIA 11,SCUOLA PRIMARIA,3,CENTRO,UMBRIA,PERUGIA,G478,PERUGIA,VIA SIMPATICA N. 22,06100,SCUOLA PRIMARIA,NORMALE,standard,1,0,16,16,1.0,1,NaN,1,12,1.0,16.0,0.0,1

In [9]:
df_unita['quota_non_italiani'].describe()

count    115454.000000
mean          0.121077
std           0.134110
min           0.000000
25%           0.022472
50%           0.080000
75%           0.176471
max           1.000000
Name: quota_non_italiani, dtype: float64